### ISSUE TITLE
Keywords filter in effective starts Microsoft.ApplicationInsights 15.0. Listener needs update accordingly.

### ISSUE THREAD

**Issue by xiaomi7732** [microsoft/ApplicationInsights-Profiler-AspNetCore#102]
This will prevent profiler to work with MS.ApplicationInsights.AspNetCore 15.0.

The symptoms are:
1. Will always get: There is no matched start activity found for this request id: `xxxx`. This could happen for the first few activities.
1. Trace validation will always fail.

**Comment by dstj** [comment]
@xiaomi7732 
You mean ApplicationInsights version 2.15.0, right?

Can I run the latest Profiler (2.2.0-beta1) on Linux with ApplicationInsights 2.14.0, then?

**Comment by xiaomi7732** [comment]
@dstj Thanks for the ask. Yes, 2.2.0-beta1 + Application Insights 2.14.0 will work.

**Comment by xiaomi7732** [comment]
Please update to use the latest bits with application insights 15.0:
https://www.nuget.org/packages/Microsoft.ApplicationInsights.Profiler.AspNetCore/2.2.0-beta2
