### ISSUE TITLE
Exception "Invalid operation on start activity cache. Fail to record the activity."

### ISSUE THREAD

**Issue by dstj** [microsoft/ApplicationInsights-Profiler-AspNetCore#103]
Using 2.2.0-beta1 w/ ApplicationInsights 2.14.0, I have got the following error in my logs.

```
    "RenderedMessage": "Invalid operation on start activity cache. Fail to record the activity.",
    "Exception": "System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
    at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
    at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
    at Microsoft.ServiceProfiler.DictionaryExtension.GetOrAdd[TKey,TValue](IDictionary`2 dictionary, TKey key, Func`2 valueFactory)
    at Microsoft.ServiceProfiler.Sampling.SampleActivityContainer.AddSample(SampleActivity activity)
    at ServiceProfiler.EventPipe.Client.EventListeners.TraceSessionListener.AppendSampleActivity(SampleActivity activity)",
```

This happened twice back to back, early on after starting the process, then no longer. And I noticed that no Upload logs are presents (no idea if that related?). I restarted the process after from scratch and the error did not occur.

Attached are all the ServiceProfiler logs leading to the error and some after (noticed another exception at L300): [profiler-error-logs.txt](https://github.com/microsoft/ApplicationInsights-Profiler-AspNetCore/files/5314885/profiler-error-logs.txt) (I tried to format the JSON logs as best I could)

Environment:
Dev workstation, Windows 10 Pro, .NET Core 3.1.402

**Comment by xiaomi7732** [comment]
@dstj thanks for your feedback. I'll take a look.

**Comment by xiaomi7732** [comment]
This could trace back to: https://github.com/dotnet/runtime/issues/26868.
I'll issue an fix to the bug.

**Comment by xiaomi7732** [comment]
The fix is released with the latest package: https://www.nuget.org/packages/Microsoft.ApplicationInsights.Profiler.AspNetCore/2.2.0-beta2
