### ISSUE TITLE
v2.2.0-beta: Unexpected error happens on stopping service profiler - System.ComponentModel.Win32Exception (2): No such file or directory

### ISSUE THREAD

**Issue by dstj** [microsoft/ApplicationInsights-Profiler-AspNetCore#108]
Hi,

I'm trying to get the profiler to run under Linux w/ .NET Core 3.1.403. I got the following exception and no trace was uploaded:

```
{
    "Timestamp": "2020-10-24T21:07:09.6662737+00:00",
    "Level": "Debug",
    "MessageTemplate": "Calling execute out of proc on {0} with arguments: {1}",
    "RenderedMessage": "Calling execute out of proc on "dotnet" with arguments: "/tmp/Microsoft.ApplicationInsights.Profiler.Uploader.dll -t "/tmp/f7bc1a01-0f8f-4555-a2e3-26352e381164.netperf" -i 3ad212ad-d872-47da-9804-341ee33908d2 -d a5707111-5df7-448f-8eab-0716e58b305f --sessionId "2020-10-24T21:04:57.8551825Z" -s "eastus-kdhwlf5sz6p6s" --host https://agent.azureserviceprofiler.net --metadata "/tmp/f7bc1a01-0f8f-4555-a2e3-26352e381164.metadata""",
    "Properties": {
        "0": "dotnet",
        "1": "/tmp/Microsoft.ApplicationInsights.Profiler.Uploader.dll -t "/tmp/f7bc1a01-0f8f-4555-a2e3-26352e381164.netperf" -i 3ad212ad-d872-47da-9804-341ee33908d2 -d a5707111-5df7-448f-8eab-0716e58b305f --sessionId "2020-10-24T21:04:57.8551825Z" -s "eastus-kdhwlf5sz6p6s" --host https://agent.azureserviceprofiler.net --metadata "/tmp/f7bc1a01-0f8f-4555-a2e3-26352e381164.metadata"",
        "SourceContext": "ServiceProfiler.EventPipe.Client.UploaderCallers.OutOfProcCaller"
    }
}
{
    "Timestamp": "2020-10-24T21:07:09.6753680+00:00",
    "Level": "Error",
    "MessageTemplate": "Unexpected error happens on stopping service profiler.",
    "RenderedMessage": "Unexpected error happens on stopping service profiler.",
    "Exception": "System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName, String arguments)
   at ServiceProfiler.EventPipe.Client.UploaderCallers.OutOfProcCaller.Execute()
   at ServiceProfiler.EventPipe.Client.TraceUploader.TraceUploaderProxy.<>c__DisplayClass2_0.<DefaultCallUploadAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at ServiceProfiler.EventPipe.Client.TraceUploader.TraceUploaderProxy.UploadAsync(DateTimeOffset sessionId, String traceFilePath, String metadataFilePath, Guid dataCube)
   at ServiceProfiler.EventPipe.Client.ServiceProfilerProvider.UploadTraceAsync(PostStopOptions options, Int32 processId)
   at ServiceProfiler.EventPipe.Client.ServiceProfilerProvider.PostStopProcessAsync(PostStopOptions e)",
    "Properties": {
        "SourceContext": "ServiceProfiler.EventPipe.Client.ServiceProfilerProvider",
        "ExceptionDetail": {
            "HResult": -2147467259,
            "Message": "No such file or directory",
            "Source": "System.Diagnostics.Process",
            "NativeErrorCode": 2,
            "ErrorCode": -2147467259,
            "Type": "System.ComponentModel.Win32Exception"
        }
    }
}
```

"ServiceProfiler" debug logs leading to that: 
[ServiceProfiler-debug-logs.txt](https://github.com/microsoft/ApplicationInsights-Profiler-AspNetCore/files/5433792/ServiceProfiler-debug-logs.txt)

Possibly (un)related, I'm not sure, but on a previous attempts (w/ server reboot in between), I had this exception:

```
{
    "Timestamp": "2020-10-24T20:04:53.4081396+00:00",
    "Level": "Error",
    "MessageTemplate": "Failed to write the trace file.",
    "RenderedMessage": "Failed to write the trace file.",
    "Exception": "System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.IO.Stream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at ServiceProfiler.EventPipe.Client.TraceControls.DiagnosticsClientTraceControl.StartWriteAsync(String traceFilePath, Stream readFrom)",
    "Properties": {
        "SourceContext": "ServiceProfiler.EventPipe.Client.TraceControls.DiagnosticsClientTraceControl",
        "ExceptionDetail": {
            "Type": "System.IO.IOException",
            "HResult": -2146232800,
            "Message": "Unable to read data from the transport connection: Operation canceled.",
            "Source": "System.Net.Sockets",
            "InnerException": {
                "HResult": -2147467259,
                "Message": "Operation canceled",
                "Source": null,
                "SocketErrorCode": "OperationAborted",
                "ErrorCode": 125,
                "NativeErrorCode": 125,
                "Type": "System.Net.Sockets.SocketException"
            }
        }
    }
}
```

--
Environment:
Linux (from the [Heroku-16 stack](https://devcenter.heroku.com/articles/heroku-16-stack))
.NET Core 3.1.403
Microsoft.ApplicationInsights.AspNetCore 2.15.0
Microsoft.ApplicationInsights.WorkerService 2.15.0
Microsoft.ApplicationInsights.Profiler.AspNetCore 2.2.0-beta2

**Comment by xiaomi7732** [comment]
@dsjt Hey, thanks for posting the callstack. That helps.

There are several potential issues here:

* Please checkout the [supportMatrix](https://github.com/microsoft/ApplicationInsights-Profiler-AspNetCore/blob/master/SupportMatrix.md). 2.2.0-beta2 will not run on .NET Core 3.1.403. Either
    * Mitigate the application to .NET Core 3.1, or
    * Downgrade profiler to [1.1.7-beta2](https://www.nuget.org/packages/Microsoft.ApplicationInsights.Profiler.AspNetCore/1.1.7-beta2).

* The first log shows your application can't access **dotnet.exe** (or the version is not expected).
    * No matter which version to use, please making sure the application can call 'dotnet.exe'. Potentially, add the path to dotnet.exe to $PATH.

* The second callstack you shared pointing to the fact that the application can't write to `/tmp`. Either:
    * Make `/tmp` writable to the app, or
    * Set the `LocalCacheFolder` variable to another writable mounting point. [Here's how to set the variable](https://github.com/microsoft/ApplicationInsights-Profiler-AspNetCore/blob/master/Configurations.md). Notice: this variable is introduced in recent versions and might not fit for .NET Core 3.1 applications.

Try figure out the proper combinations for your app and feel free to post more info if you need more assistant.

**Comment by dstj** [comment]
@xiaomi7732 Thanks for your help. I had never thought about `dotnet.exe` itself being the file not found, but that makes sense under Heroku's Linux Stack. I didn't realize that the profiler would be calling an external dotnet process for the upload. I'll try to see if can modify the runtime $PATH.

If not, any way to specify the `dotnet.exe` location from the config? Similar to the `LocalCacheFolder config variable`. I didn't see it in the config options page...

**Comment by xiaomi7732** [comment]
Hi @dstj, thank you for the quick turn-around.

Sorry, there is no existing way to set the path to **dotnet.exe**. The main reason to make upload out of proc is to avoid uploader crash the app by accident.

That said, if you really have to have a configuration to specify **a full path to dotnet.exe**, submit a PR for a feature request & we will evaluate it. It just the implementation might **NOT** be as fast as you might want it to.

Feel free to let us know.

**Comment by dstj** [comment]
Thanks @xiaomi7732. I fixed my PATH and now get traces uploaded (and some more "Failed to write the trace file" exceptions, but I'll create another issue for those)

**Comment by xiaomi7732** [comment]
I am glad to know that it worked.
