### ISSUE TITLE
v2.2.0-beta: Linear memory consumption increase. Is this expected?

### ISSUE THREAD

**Issue by dstj** [microsoft/ApplicationInsights-Profiler-AspNetCore#110]
Hi (again ;) ),

I just deployed the v2.2.0-beta in my production (low volume production) environment and here's is the memory graph:

![image](https://user-images.githubusercontent.com/467692/97619280-6873c980-19f6-11eb-985a-29617bf2601c.png)

That first steady linear increase over 4 hours is when the `ServiceProfiler` was active. I then turned it off with the `ServiceProfiler__IsDisabled` setting (no other code change), then on again this morning and off again.

From [this documentation page](https://github.com/microsoft/ApplicationInsights-Profiler-AspNetCore/blob/master/ProfilerSessions.md) about the profiler life cycles, I see: 

> ### Session life cycles
> Running Profiler comes with overheads. It is **not** wise to keep profiler always running. Application Insights Profiler splits the profiling into sessions.
>
> By default, a typical profiling session lasts for 2 minutes. During these 2 minutes, stacks are sampled and the data are all serialized into the memory called a Circular Buffer. At the end of the 2 minutes, the buffer will be dump into a trace file (*.netperf).
>
> After finish one session, the Profiler will idle for 58 minutes, waiting for the next session to start.

So I was expecting memory spikes, not a steady linear increase.

Is this expected or could there be a memory leak in there somewhere?

Thanks.
--
Environment:
Linux (from the Heroku-16 stack)
.NET Core 3.1.403
Microsoft.ApplicationInsights.AspNetCore 2.15.0
Microsoft.ApplicationInsights.WorkerService 2.15.0
Microsoft.ApplicationInsights.Profiler.AspNetCore 2.2.0-beta2

**Comment by xiaomi7732** [comment]
@dstj Thank you for the feedback. Yes, memory spike is expected, not leaking. Heroku is a environment that is not easy for us to debug. I will spend some time to see if I could reproduce this issue on our side for further investigation.

**Comment by dstj** [comment]
Thanks @xiaomi7732 for looking into this.

I'm using my fork of the Heroku [`dotnet-buildpack`](https://github.com/dstj/dotnetcore-buildpack) to install .NET Core on top of the [`heroku-16` stack](https://github.com/heroku/stack-images). Its docker image is available if need be, but I'm guessing any Linux installation will do.

**Comment by xiaomi7732** [comment]
@dstj I want to post a status update. I reproed the issue on a local ubuntu environment. We are seeing increasing in memory working set but **not** seeing a same trending GC Heap increasing. That ruled out the managed code leaking. **More time is needed** to come down to find out what is happening on the native memory usage.

One quick question that might help analysis: do you have a memory cap on the container? Would you mind share that with us?

Thanks.

**Comment by dstj** [comment]
@xiaomi7732 

Thanks for the follow up. I do, it's 1GB. Though it is a soft limit as I went over a few times and received alerts. The hard limit may be 1.1 GB... I don't know that for sure.

**Comment by xiaomi7732** [comment]
@dstj Hey, thanks for the patient. It took us a while to hunt down the memory issue. Some deeper analysis needed aside, we have a build that addresses the linear memory consumption issue.

Here's the test result on our side. On the chart below shows the memory available for a couple of days on a Ubuntu virtual machine with Profiler enabled. Before the fix, there are around 1G consumption per 24 hours. After the fix, the consumption is gone:
![image](https://user-images.githubusercontent.com/3674549/99609823-77caaf00-29c5-11eb-94a4-c45701a54b5b.png)

We will release the new build as soon as possible:

**Comment by dstj** [comment]
@xiaomi7732 Thanks for looking into that issue! Looking forward to the next release.

**Comment by xiaomi7732** [comment]
Released in [2.2.0-beta4](https://www.nuget.org/packages/Microsoft.ApplicationInsights.Profiler.AspNetCore/2.2.0-beta4).
