### ISSUE TITLE
With an invalid AppInsight instrumentation key I got "No stamp id is fetched. Abort the upload process." error message

### ISSUE THREAD

**Issue by jeremymeng** [Microsoft/ApplicationInsights-Profiler-AspNetCore#12]
It would be great to have a better error message to indicate that the key is invalid.

**Comment by xiaomi7732** [comment]
Thanks for filing the issue. There could be various reasons why the StampId couldn't be fetched, invalid iKey is one of them.

That said, I'll look into how to emit a better message.

**Comment by xiaomi7732** [comment]
https://www.nuget.org/packages/Microsoft.ApplicationInsights.Profiler.AspNetCore/1.1.3-beta1
