### ISSUE TITLE
Consider adding Microsoft.ApplicationInsights.AspNetCore as a dependency in 2.1-based package

### ISSUE THREAD

**Issue by jeremymeng** [Microsoft/ApplicationInsights-Profiler-AspNetCore#13]
In ASP.NET Core 2.1, the default project template does not pull in the `Microsoft.ApplicationInsights.AspNetCore` so I had to add it in order for the newer 2.1-based profiler package to work.  It is better to specify it as a dependency so end users don't need to include it by themselves.

**Comment by xiaomi7732** [comment]
https://www.nuget.org/packages/Microsoft.ApplicationInsights.Profiler.AspNetCore/1.1.3-beta1
