### ISSUE TITLE
Add Operation ID to Profile Tree Page

### ISSUE THREAD

**Issue by ericmattingly** [microsoft/ApplicationInsights-Profiler-AspNetCore#131]
The Operation ID shown in the "End-to-end Transactions Details" blade is very interesting to us since we can use it as a correlation id with logs outside of Application Insights.

Can we add the same to the Profile Tree Page up where it listed the Process ID and Activity ID?

![image](https://user-images.githubusercontent.com/10789017/107174184-6bc80b00-697e-11eb-86fc-ba9914c2e78a.png)

**Comment by xiaomi7732** [comment]
Hi @ericmattingly Thanks for filing the issue. I have added this to our backlog. While the UI work will take a while for implementation, here's a quick work-around:

![image](https://user-images.githubusercontent.com/3674549/107275887-2a2f7280-6a07-11eb-9e9c-5cd140574a3a.png)

1. Download the trace file & rename it to *.netperf.zip;
1. Open the trace file in [perfview](https://github.com/microsoft/perfview);
1. Open 'Events' pane;
2. Find events provider named 'Microsoft-ApplicationInsights-DataRelay';
3. Use the 'Column' options to display **operationIds**;

Feel free to let me know if you need further info.

**Comment by xiaomi7732** [comment]
This has been tracked. I'll close this issue for now. Feel free to open new issues.
