### ISSUE TITLE
Profiler might stop working after days of running

### ISSUE THREAD

**Issue by xiaomi7732** [microsoft/ApplicationInsights-Profiler-AspNetCore#135]
There is a deadlock found in .NET Core CLR that will happen in a rare case.
While we are looking into how to fix it, it will take a while before it could be fixed and back ported to .NET Core 3.x.

Workaround:
* Restart the app.

Tracking of fix in `dotnet/runtime` repo: https://github.com/dotnet/runtime/issues/51579

**Comment by xiaomi7732** [comment]
Hi @polage-tr Thanks for the ask. Could you please re-post it on the linked issue for dotnet/runtime here: [#51579](https://github.com/dotnet/runtime/issues/51579). According to the info there, the fix is in .NET 5, but hasn't been back ported to .NET Core 3.1. And since the issue is in .NET Core runtime, it impacts all versions of the applications/profilers running on it.

**Comment by polage-tr** [comment]
@xiaomi7732 thank you for the reply will repost my quetion.

**Comment by xiaomi7732** [comment]
Close due to external issues and not actionable on this. Feel free to reopen if there's other things that we can do.
