### ISSUE TITLE
How to open downloaded .netperf file?

### ISSUE THREAD

**Issue by ins4n333** [microsoft/ApplicationInsights-Profiler-AspNetCore#14]
Is it any way to view downloaded .netperf  files using some desktop tools like perfview or others?

**Comment by pharring** [comment]
Yes, [PerfView](https://github.com/Microsoft/perfview) can load .netperf files.

**Comment by ins4n333** [comment]
I have a few more questions
Does the profiers works on containers that are not facade services (which do not provide api). For example, on some background message handlers or similar?
How exactly do you collect the traces? Using perfview in the trace file  I see not only requst stacks, but there are also a lot of useful  dotnet events. Which is very cool. Is this information obtained using the  utilities like Perf + Littng or you use some different frameworks?

**Comment by pharring** [comment]
@xiaomi7732 can you help?

**Comment by xiaomi7732** [comment]
@ins4n333 thanks for your asking.
If I understand right, you want to know if Application Insights Profiler runs on applications that run on its own, right? The profiler will work as long as your application runs on .NET Core CLR 2.1 and above and the container can have outbound traffic to talk with the service profiler service (thus to upload the netperf gathered). That said, application profiler is relatively new, there might be edge cases that it doesn't run. You are welcome to file issues here when specific scenarios are not working and we can troubleshoot it.

With regarding the trace gathering, no, we are not using Perf+Littng. The traces are collected by a new implementation in .NET Core CLR named EventPipe. Feel free to ask specific questions around it here. Or you can also go to https://github.com/dotnet/coreclr to ask questions directly related to EventPipe.
