### ISSUE TITLE
Look into remove the dependency on Newtonsoft.Json

### ISSUE THREAD

**Issue by xiaomi7732** [microsoft/ApplicationInsights-Profiler-AspNetCore#142]
Use `System.Text.Json` that shipped with .NET Core runtime will reduce the size of the package. Look into how much will it take to implement it.

**Comment by Matthewsre** [comment]
I'm using a .net 5 asp.net web api and there are no dependencies on Newtonsoft.Json. This caused a runtime error since the dependency wasn't identified through nuget.

**Comment by xiaomi7732** [comment]
@Matthewsre Are you saying your project isn't have an explicit or implicit dependent on `Newtonsoft.Json` today? That is weird. Although `Newtonsoft.Json` isn't depended upon by `Microsoft.ApplicationInsights.Profiler.AspNetCore`, it is depended on by `Microsoft.ApplicationInsights.Profiler.Core`, which is dependent on by the ASPNetCore package.

In other words:
Your project -> Microsoft.ApplicationInsights.Profiler.AspNetCore -> Microsoft.ApplicationInsights.Profiler.Core -> Microsoft.ApplicationInsights.Profiler.Core -> Newtonsoft.Json

Do I misunderstand your issue or could you please double check the dependency tree?

If you all check out, could you please file a new issue with the result from this cli:

```shell
dotnet list package --include-transitive
```

Much appreciated for the feedback!

**Comment by xiaomi7732** [comment]
Released in https://www.nuget.org/packages/Microsoft.ApplicationInsights.Profiler.AspNetCore/2.4.0-beta1.
