### ISSUE TITLE
Switching off the triggers by default

### ISSUE THREAD

**Issue by GeorgeChackungal** [microsoft/ApplicationInsights-Profiler-AspNetCore#145]
Hi,

Is there a way I can add the profiler to a containerized app with all the triggers off? And only run the "Profile Run" from azure when I need it?

**Comment by xiaomi7732** [comment]
Hi @GeorgeChackungal Thanks for the ask. That functionality is not officially supported. Is there a reason or concern that you want all the triggers off?

**Comment by GeorgeChackungal** [comment]
Do the team have any plan to support this in the future?

We wanted to run the profiler only when we encounter some failures etc. Also, we are not sure about the performance impact of having this enabled all the time.

**Comment by GeorgeChackungal** [comment]
Any update on the above?

**Comment by xiaomi7732** [comment]
Hi @GeorgeChackungal, sorry for the delay. Here's what we usually do for that scenario:
1. Enable Profiler with this settings in an environment variable:

```shell
ServiceProfiler__IsDisabled=True
```

2. Set the value to `False` when profiler needs to be turned on.

For more configurations, refer to [Configurations](https://github.com/microsoft/ApplicationInsights-Profiler-AspNetCore/blob/main/Configurations.md).

Will that address your scenario?

Thanks!
