### ISSUE TITLE
Allow specific Instrumentation Key to be provided

### ISSUE THREAD

**Issue by ransagy** [microsoft/ApplicationInsights-Profiler-AspNetCore#147]
Unlike most of the other AI NuGet packages, There is no way to provide the Instrumentation Key explicitly for this library, Instead relying on one env var to be available at all times.

This is an issue if the same AI key isn't wanted on telemetry collection for the normal AI library or in any 3rd party code that instanciates their own `TelemtryConfiguration`.

Would it be possible to align with the other AI libraries and provide a way to explicitly set/override this?

**Comment by xiaomi7732** [comment]
Hi @ransagy, thanks for the feedback. I am trying to understand how to prioritize this work. We don't usually get back feedback that there are multiple iKeys in the same application. Could you please explain why do you want to have multiple iKeys in the same app? It would be great if you could describe your scenario specifically.

**Comment by xiaomi7732** [comment]
Not getting back for a while. Close this one for now. Feel free to raise new issues.
