### ISSUE TITLE
Remove dependency on Newtonsoft.Json - i2

### ISSUE THREAD

**Issue by xiaomi7732** [microsoft/ApplicationInsights-Profiler-AspNetCore#163]
- [ ] Bump up the dependency to `microsoft.applicationinsights.windowsserver.telemetrychannel` to 2.15 +
- [ ] Update the code in `ConfigureUserConfiguration.cs` as well as `ServiceProfilerStartupFilter.cs`.
- [ ] Convert other places that still uses Newtonsoft.Json for serialization.

For testing, please bump up MS.ApplicationInsights.AspNetCore to 15.0+ to avoid bringing in Newtonsoft.Json on the dependency tree.

**Comment by pjquirk** [comment]
Does this include the `Newtonsoft.Json.Schema` library as well? It's license is AGPL-3.0-only, which is currently problematic for us since it's unclear we can use it directly.

**Comment by xiaomi7732** [comment]
@pjquirk Thanks for the ask. @JacobBovee , could you please answer that?

**Comment by JacobBovee** [comment]
Hey @pjquirk yep this includes `Newtonsoft.Json.Schema`. The next package release will include this change and we should be getting that out really soon.

**Comment by xiaomi7732** [comment]
Released: https://www.nuget.org/packages/Microsoft.ApplicationInsights.Profiler.AspNetCore/2.4.0-beta1
