### ISSUE TITLE
No profiler upload on net6 in AKS

### ISSUE THREAD

**Issue by CodedBeard** [microsoft/ApplicationInsights-Profiler-AspNetCore#172]
We've been trying to get the profiler to work for our aspnet core app running in AKS. While forcing a profiling session from the portal appears to correctly start the tracing, the results are never uploaded to the portal, and no errors are recorded anywhere that we can find.

If we exec into the container, we can see there is a `TraceUpload.zip` file being created in the container, but there are no logs to suggest why the upload keeps timing out.

Versions Used:
```
SDK: Net6
Container: mcr.microsoft.com/dotnet/aspnet:6.0.0-bullseye-slim-amd64
Nugets

<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.19.0" />
<PackageReference Include="Microsoft.ApplicationInsights.Kubernetes" Version="2.0.3" />
<PackageReference Include="Microsoft.ApplicationInsights.Profiler.AspNetCore" Version="2.4.0-beta1" />
```

We also tried using the 2.3.1 version of the package, but that had the same issue.

**Comment by xiaomi7732** [comment]
@CodedBeard, thank you for filing the issue. I am sorry to hear that Profiler's not working for you.

There are various reasons to not having any profiling trace. I'd like to know more for troubleshooting.

Just for some quick check:

Firstly, during the profiling session, is there traffic to your application? No traffic no profile :-)
Secondly, do you have a writable folder on your container for uploader to work? We assume `/tmp` to be writable but there had been exceptions and we need special settings for those read-only environments.

If those don't hit, we will need logs to tell us what is going on.

Could you please turn on logs for category of `Microsoft.ApplicationInsights.Profiler` and see what is missing?

Just in case, one quick way to do it is, in `appsettings.json`, you add/append:

```jsonc
{
...
  "Logging": {
    "LogLevel": {
      "Default": "...",  // You might have some other settings
      "Microsoft.ApplicationInsights.Profiler": "Debug" // Turn on debug logs for Profiler
    }
  }
...
}
```

Refer to [Configurations](https://github.com/microsoft/ApplicationInsights-Profiler-AspNetCore/blob/main/Configurations.md) for more details on configuration. I would suggest you start with `Debug` and if necessary, use `Trace`.

You should see information like Profiler started, activity captured, and when the session is ready for uploading, how is uploader located and more. See if there's error or warnings.

If you want, post the logs and I can help take a look as well.

**Comment by CodedBeard** [comment]
Thanks for the tips @xiaomi7732.

Yes, there is definetly traffic hitting the system, as we are in the process of testing a large new release :)

I've got to go to a conference today, but will give the other suggestions a try when im back.

**Comment by xiaomi7732** [comment]
Please let us know.

**Comment by CodedBeard** [comment]
@xiaomi7732 I've confirmed that /tmp is writtable within the containers.

After enabling the Debug logging level, we've found the following exception being thrown:

```
{"EventId":0,"LogLevel":"Debug","Category":"Microsoft.ApplicationInsights.Profiler.Core.Orchestration.RemoteProfilerSettingsService","Message":"Unexpected error contacting service profiler service endpoint for settings. Details: System.ArgumentNullException: Value cannot be null. (Parameter \u0027command\u0027)\n   at Microsoft.ServiceProfiler.DataContract.Settings.SettingsParser.ParseAgentSettings(String command, AgentSettings baseSettings)\n   at Microsoft.ServiceProfiler.DataContract.Settings.SettingsParser.ParseManyAgentSettings(String[] commands, AgentSettings baseSettings)\n   at Microsoft.ApplicationInsights.Profiler.Core.Contracts.ProfilerSettings.SetFromSettingsContract(SettingsContract settingsContract)\n   at Microsoft.ApplicationInsights.Profiler.Core.Orchestration.RemoteProfilerSettingsService.FetchRemoteSettingsAsync(CancellationToken cancellationToken)","State":{"Message":"Unexpected error contacting service profiler service endpoint for settings. Details: System.ArgumentNullException: Value cannot be null. (Parameter \u0027command\u0027)\n   at Microsoft.ServiceProfiler.DataContract.Settings.SettingsParser.ParseAgentSettings(String command, AgentSettings baseSettings)\n   at Microsoft.ServiceProfiler.DataContract.Settings.SettingsParser.ParseManyAgentSettings(String[] commands, AgentSettings baseSettings)\n   at Microsoft.ApplicationInsights.Profiler.Core.Contracts.ProfilerSettings.SetFromSettingsContract(SettingsContract settingsContract)\n   at Microsoft.ApplicationInsights.Profiler.Core.Orchestration.RemoteProfilerSettingsService.FetchRemoteSettingsAsync(CancellationToken cancellationToken)","0":"System.ArgumentNullException: Value cannot be null. (Parameter \u0027command\u0027)\n   at Microsoft.ServiceProfiler.DataContract.Settings.SettingsParser.ParseAgentSettings(String command, AgentSettings baseSettings)\n   at Microsoft.ServiceProfiler.DataContract.Settings.SettingsParser.ParseManyAgentSettings(String[] commands, AgentSettings baseSettings)\n   at Microsoft.ApplicationInsights.Profiler.Core.Contracts.ProfilerSettings.SetFromSettingsContract(SettingsContract settingsContract)\n   at Microsoft.ApplicationInsights.Profiler.Core.Orchestration.RemoteProfilerSettingsService.FetchRemoteSettingsAsync(CancellationToken cancellationToken)","{OriginalFormat}":"Unexpected error contacting service profiler service endpoint for settings. Details: {0}"}}
```

**Comment by xiaomi7732** [comment]
Hey @CodedBeard 
Thanks for the info.

Based on what provided, I have 2 points that I want to share with you:

1. The call stack points to a bug in our code base that null is not well checked before calling parser
    1. While we are here, do you mind **share your iKey** with us (mail me: saars@microsoft.com, or whatever way you are comfortable with)? It is interesting to see what the profiler settings you have in our backend to understand why we will encounter null case.
1. However, that is not the reason for profiler not working because the success to that method is optional.
    1. While you have the settings, can you share the console log for the first few minutes (2 to 3 minutes) on starting the pods? I'd like to dig more into why profiler is not happening. 

### Details

* This is the code that not checking null well, worth a fix.
  ```csharp
  // Any line to be null in this code could leading to ArgumentNullException for the parser
  string[] settingsToParse = {
      settingsContract.CollectionPlan,
      settingsContract.CpuTriggerConfiguration,
      settingsContract.MemoryTriggerConfiguration,
      settingsContract.DefaultConfiguration
  };
  AgentSettings parsedSettings = SettingsParser.Instance.ParseManyAgentSettings(settingsToParse);
  ```

* This is why it is optional for successful profiling:

  ```csharp
  #pragma warning disable CA1031 // Only to allow for getting the value for the next iteration. The exception will be logged.
  catch (Exception ex)
  #pragma warning restore CA1031 // Only to allow for getting the value for the next iteration. The exception will be logged.
  {
      // Move on for the next iteration.
      _logger.LogDebug("Unexpected error contacting service profiler service endpoint for settings. Details: {0}", ex);
  }
  ```

**Comment by CodedBeard** [comment]
Thanks @xiaomi7732.

I've sent you a mail with the Ikey and the log buffer from the pod.

One thing I've noticed, is it appears that error has now stopped, and the `RandomSchedulingPolicy` seems to have started firing and uploading results. But attempts to start a profiling session from the portal are still resulting in a timeout error.

**Comment by xiaomi7732** [comment]
Hey @CodedBeard Thanks for the updating and the logs.

_Unfortunately there's no timestamp on the log so I can't tell when_. But here's what I observed:

1. The exception we mentioned in the last conversation was resolved about half way of the logs (line 3397) - combing it with our backend data, I assume you or someone owns your application insights resource at that moment somehow touched the settings of the profiler on the portal, that's when the buggy code path got bypassed.

2. I was thinking the remote settings shouldn't impact the execution of the profiler, however, I might oversighted the fact that bad settings (by exception) might trick the agent to think that OnDemand policy or other policy got disabled. We will need to investigate more about it.

At the same time, I am leaning toward changing the Profiler settings, thus generate the settings instead of using default, is a work around, just in case anyone encountered the same:

![image](https://user-images.githubusercontent.com/3674549/169363866-09770f47-bf0a-4406-bc44-ac63ff0acc77.png)

I'd keep this issue open until we reach the bottom of the investigation.

**Comment by CodedBeard** [comment]
@xiaomi7732 Ah, now you mention it, I did try lowering the memory threshold to below what I knew the pod was using at some point to see if that would cause it to work, but as far as I recall, it was a good hour or so before the first trace fired which is why I completely forgot about it. 

That was certainly the first and only time I changed the `Trigger` settings (and I'm the only one who has access to do so), so I think the hypothesis that doing so fixed the settings error makes sense.

**Comment by xiaomi7732** [comment]
@CodedBeard Thanks for the quick turn-around. I think we have enough information at this point to find out the root cause. Thank you so much for providing the information.

**Comment by CodedBeard** [comment]
For the branch I just applied it to, no, there are no entries yet.

The original branch fired twice on the `RandomSchedulingPolicy` with memory values of 92% and 89% before the `Profile now` first succedded.

**Comment by xiaomi7732** [comment]
Thank you for the confirm!

**Comment by xiaomi7732** [comment]
Hey @CodedBeard, while @JacobBovee is actively working on fixing the bug, we are looking forward to hear back from you about the investigation on the other branch, if you are willing to share. And we will let you know when there's a newer package that you could try on for the bug fix.

**Comment by CodedBeard** [comment]
Hi @xiaomi7732, sorry for the delay, I've been super busy at work.

Due to being focused on other projects i hadn't checked the other branch in a while, but i've just looked this morning and can see the profiler has since been firing correctly based on cpu/memory usage.

**Comment by xiaomi7732** [comment]
@CodedBeard, No worries. I am glad to hear back from you :-) Actually, we released 2.4.0 with the bug fix and you don't need the workaround any further. Feel free to give it a shoot:
https://www.nuget.org/packages/Microsoft.ApplicationInsights.Profiler.AspNetCore/

**Comment by CodedBeard** [comment]
@xiaomi7732 Great, I'll be deploying the updated package to prod this evening, will let you know if it all works.

**Comment by CodedBeard** [comment]
@xiaomi7732 Have now deployed 2.4 package to production and everything worked first time without having to change the settings, so looks like this can be closed now thanks.

**Comment by xiaomi7732** [comment]
Thank you @CodedBeard. I am glad to hear that. Thanks for the prompt replies. With your help, Profiler is better now :-D
