### ISSUE TITLE
Null exception in Settings Contract when settings do not exist. 

### ISSUE THREAD

**Issue by JacobBovee** [microsoft/ApplicationInsights-Profiler-AspNetCore#174]
Refer to #172 for more info. Currently when remote settings do not exist they are deserialized as null breaking parsing and throwing an exception. This should not break profiling.

**Comment by xiaomi7732** [comment]
Hey @JacobBovee , do you mind also double check, for users that don't have profiler settings on our backend, are policies like OnDemand working?

I have a **hypothesis** that when there's no settings, the profiler might just not working - b/c everything would be treated as disabled and it overwrites the local settings.
