### ISSUE TITLE
Application Insights Profiler causing high memory usage

### ISSUE THREAD

**Issue by vigneshmsft** [microsoft/ApplicationInsights-Profiler-AspNetCore#188]
I have an AspNetCore (.NET 6) application running on Azure App Services and decided to enable application insights and profiler in our production environment this week as we were preparing for a larger rollout of our application.
The application is packed as a docker container and runs as a linux container web app in App Services. 
App Services plan is `P2V2`.

I noticed the increase in CPU and memory usage right after the change and disabled random sampling from application insights profiler interface in Azure portal and only had it to profile if it exceeded a CPU or memory threshold.
I understand profiling can increase CPU and memory usage but the average memory usage was 10x the usual average for my application and also when the profiler was not running. 
There was a noticeable increase in the CPU% for the app service too.

Memory usage after enabling AddServiceProfiler() using default configuration.
![image](https://user-images.githubusercontent.com/10269434/202561156-92cd1df0-b82b-41f6-8f60-e7cb7858568d.png)
 The drop in memory usage back to the normal ~150MB is when I removed the AppServiceProfiler() config in code and redeployed.
 
 Environment: Azure App Service P2V2
 AspNetCore 6.0.11 running as docker container 
 
 nuget package versions:
 `Microsoft.ApplicationInsights.AspNetCore (2.21.0)`
 `Microsoft.ApplicationInsights.Profiler.AspNetCore (2.5.0)`

**Comment by xiaomi7732** [comment]
Hi @vigneshmsft Our memory sampling shows a level of usage increasing but not 10x as much:

![image](https://user-images.githubusercontent.com/3674549/202586110-0fad52a8-2bad-46de-a468-030f6f819e7b.png)
(WorkingSet in MB)

When you evaluate the memory usage, was it the usage for the whole app service plan? How many application instances were there on the plan? Were they running profiling at the same time?

**Comment by vigneshmsft** [comment]
there is only one app on the plan, it was running 2 instances at the time, I also have a deployment lot for the production instance.

**Comment by vigneshmsft** [comment]
the attached image was the usage metric for the app and not the app service as whole.

**Comment by xiaomi7732** [comment]
Hi @vigneshmsft, I deployed a containerized .NET 6 webapi to a P2V2 plan for testing the profiler, here's my results:

![image](https://user-images.githubusercontent.com/3674549/209994549-78fe02fd-e0a9-46ce-baf8-fbbf05d50dd6.png)

 I still can't see what was described. Am I looking into the same metrics as you do?

To further troubleshoot, we need to understand what is taking the memory. Is it possible for you to take 2 memory dumps, one before the high usage, and the other during the profiler, when the memory usage is higher, so that we can compare the dumps to see what actually is using the memory?

**Comment by xiaomi7732** [comment]
Hi Vigneshmsft, okay. Thanks for the update. Let's us know if you decide to give it another shoot.
