### ISSUE TITLE
User report: Memory usage is almost always > 90% on Linux, investigate why

### ISSUE THREAD

**Issue by xiaomi7732** [microsoft/ApplicationInsights-Profiler-AspNetCore#197]
It looks like, on Linux, the memory usage is almost always > 90%, which will fire the memory trigger continuously.
Currently, memory usage is using meminfo of Linux, the rate is computed by MemFree / MemTotal:

For example:

```shell
saars@Linux:~$ cat /proc/meminfo
MemTotal:       16312820 kB
MemFree:        16168040 kB
MemAvailable:   16033164 kB
Buffers:            5984 kB
...
```

Considering how Linux allocates memory:
https://serverfault.com/questions/85470/meaning-of-the-buffers-cache-line-in-the-output-of-free

**Comment by xiaomi7732** [comment]
And here's the proof of it:
![image](https://github.com/microsoft/ApplicationInsights-Profiler-AspNetCore/assets/3674549/9200c591-58db-4e3a-af55-a8a77c65e01c)

**Comment by xiaomi7732** [comment]
@mumustafa, thanks for chiming in. I am considering a simpler calculation of:
1 - available / total

Here are my reasons:
1. According to [the spec](https://man7.org/linux/man-pages/man5/proc.5.html):
    ```text
              MemAvailable %lu (since Linux 3.14)
                     An estimate of how much memory is available for
                     starting new applications, without swapping.
    ```
    And that's what the user actually cares about - how much memory is available.

2. It's more accurate
    * In a system that is heavily buffered, using your example, there's not **too much difference**:
        1 - (free + available) / total = 1 - (81 + 532) / 1790 = 66%, compare to:
        1 - available / total = 1 - 532 / 1790 = 70%

    * However, in a system that is not heavily buffered, like this one on a WSL:
      ![image](https://github.com/microsoft/ApplicationInsights-Profiler-AspNetCore/assets/3674549/05d4f8c5-aa8a-471c-9d6d-e909ebf7a84f)
       1 - (free + available) / total = 1 - (11906 + 14246) / 15930 = -64% <---- this negative number doesn't make sense. And compare to:
       1 - available / total = 1 - 14246 / 15930 = 11%

The big difference I see, is that available + free might exceed total while available is always less than the total.

Any inputs?

**Comment by mumustafa** [comment]
@xiaomi7732 I think you're 100% on point, I was also looking at it from the free command as well: https://man7.org/linux/man-pages/man1/free.1.html
![image](https://github.com/microsoft/ApplicationInsights-Profiler-AspNetCore/assets/109315042/46da6376-46c7-4f57-8c16-3291ecbf6a05)
Looking at the commit description:  https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773 also confirms your findings.

**Comment by mumustafa** [comment]
[heart]         Mustafa Mustafa reacted to your message:
________________________________

**Comment by xiaomi7732** [comment]
Thank you for bringing this up!

**Comment by xiaomi7732** [comment]
Stable package released:
https://www.nuget.org/packages/Microsoft.ApplicationInsights.Profiler.AspNetCore/2.5.3
