### ISSUE TITLE
Update the document to state clearly that 'Enable Profiler' button is not needed in AppInsights-Profiler-AspNetCore for Linux

### ISSUE THREAD

**Issue by xiaomi7732** [Microsoft/ApplicationInsights-Profiler-AspNetCore#2]
@CawaMS As we discussed offline, could you please update the document, find a proper place to state this clear? Thanks!

**Comment by CawaMS** [comment]
https://docs.microsoft.com/en-us/azure/application-insights/app-insights-profiler-aspnetcore-linux#known-issues
