### ISSUE TITLE
Failed adding start activity: /#1/1/4/ 

### ISSUE THREAD

**Issue by ins4n333** [Microsoft/ApplicationInsights-Profiler-AspNetCore#20]
Hi
After first start profiler has been able to collect some traces,
But next runs were failed with such errors:

{"Timestamp":"2018-08-09T12:05:01.3892611+00:00","Level":"Information","MessageTemplate":"Service Profiler session started.","Properties":{"SourceContext":"ServiceProfiler.EventPipe.Client.Schedules.TraceSchedule","ConversationId":"(none)","ProfilingContext":"(none)"}}

{"Timestamp":"2018-08-09T12:05:29.3812704+00:00","Level":"Warning","MessageTemplate":"Failed adding start activity: /#1/1/4/","Properties":{"SourceContext":"ServiceProfiler.EventPipe.Client.EventListeners.TraceSessionListener","ConversationId":"(none)","ProfilingContext":"(none)"}}

{"Timestamp":"2018-08-09T12:05:30.0249730+00:00","Level":"Information","MessageTemplate":"There is no matched start activity found for this activity: id /#1503500717/. This could happen for the first few activities.","Properties":{"SourceContext":"ServiceProfiler.EventPipe.Client.EventListeners.TraceSessionListener","ConversationId":"(none)","ProfilingContext":"(none)"}}

What does it means?

**Comment by xiaomi7732** [comment]
@ins4n333 Hey, thanks for reporting this. Could you please provide a bit more details to help us understand what is going on:
1. What is your CLR version: `dotnet --info`
2. What is your project type? Is it ASP.NET Core MVC? Or is it webapi?
3. What's your hosting environment?
On Linux? On Windows + Docker Tools? Visual Studio + Docker Tools?
4. Does this 'Failed to adding start activity' or 'There is no matched start activity found' happens multiple times or just one time?
5. If possible, could please send the full log to serviceprofilerhelp@microsoft.com for analysis? Please put Linux Profiler in the title that I will be able to recognize and pick it up from there.

Thanks!

**Comment by xiaomi7732** [comment]
@ins4n333 We haven't got the mail. Is there any update?

**Comment by xiaomi7732** [comment]
Close due to no response. Please reopen if there's any update.
