### ISSUE TITLE
Instructions for EnableServiceProfilerInVS sample are a bit outdated with respect to Docker tooling

### ISSUE THREAD

**Issue by karolz-ms** [Microsoft/ApplicationInsights-Profiler-AspNetCore#21]
Starting with Visual Studion 15.8 enabling Docker does not automatically add a `docker-compose.yml` file to the project. You need to do an extra step of right-clicking the project and doing Add | Container Orchestrator Support:

![image](https://user-images.githubusercontent.com/15271049/46315934-92423400-c583-11e8-98e3-d195f66a71fc.png)

**Comment by xiaomi7732** [comment]
Fixed by #30.
