### ISSUE TITLE
When you publish an update for Microsoft.ApplicationInsights.Profiler.AspNetCore, don't mark the previous version as deprecated immediately

### ISSUE THREAD

**Issue by KirkMunroSagent** [microsoft/ApplicationInsights-Profiler-AspNetCore#219]
Reposting https://github.com/microsoft/ApplicationInsights-Profiler-AspNetCore/discussions/217 as an issue, since it seems that Discussions aren't really used in this repository.

> This idea comes from the perspective of someone who does package management.
>
> Whenever a new Microsoft.ApplicationInsights.Profiler.AspNetCore package is published, whoever publishes that package also marks the previous version as deprecated. This is different behavior than what is done on any other Microsoft.* nupkg. The challenge is that when you mark the previous version of Microsoft.ApplicationInsights.Profiler.AspNetCore as deprecated, it causes a little warning sign to appear in the NuGet Package Manager UI in Visual Studio, because suddenly projects are using a deprecated version of a package. That warning is not appropriate, because projects are fine to continue using the previous version, at least for a while.
>
> The problem with this approach is that it masks nupkgs that really need attention. For example, if a package is found to have a known vulnerability, but that vulnerability is not very severe, a warning icon can show up in the Nuget Package Manager UI in Visual Studio. That is something that really should be getting the attention of a package manager, because they need to look into the warning details so that they can triage the package update appropriately. When a new version of Microsoft.ApplicationInsights.Profiler.AspNetCore is published, by marking the previous version as deprecated, you are potentially masking real warnings that need attention. Imagine if every product team that published NuGet packages marked all of their old versions as deprecated. Suddenly we'd have warnings on every package all of the time, making those warnings absolutely useless.
>
> All to say, by marking a previous version as deprecated when you publish a new package, you are taking the wrong approach because it sets the expectation that the package needs attention right away, which is not the case. Please change your publishing strategy such that you only mark an old version as deprecated if it is truly not expected to work anymore.

**Comment by xiaomi7732** [comment]
Hey @KirkMunroSagent, I am sorry that I can't get back to you earlier for the discussion or for this bug filed.

I agree with you that deprecating packages at the moment of releasing the new package is **too aggressive**. As you pointed out, it generates warnings, and it also masks the real need of deprecating.

The other side, in the sprit of keeping things relative up to date, it is our interest to push forward the new bits, which usually carry more secure dependencies.

With those considerations, how about to having a grace period of the previous released package, what about a minimum of 30 days, given there's no known vulnerability?

Thanks.

**Comment by KirkMunroSagent** [comment]
A great period would be a welcome improvement. 30 days feels short though. Even with agile development, packages might not be updated within 30 days, depending on how the dev cycle is laid out. I think a grace period of 45 or 60 days would be more appropriate. It would certainly do the trick for my place of work. It also encourages a regular package management cycle without being too overbearing.

**Comment by xiaomi7732** [comment]
@KirkMunroSagent, 45 days sounds like a start point. Let's try it and if that still cause issues, either too long or too short, we can always tweak later, agree?

**Comment by KirkMunroSagent** [comment]
@xiaomi7732 Yes, I agree. It will be a good step in the right direction, and we'll see if it needs to be tweaked later. Thank you for this.

**Comment by xiaomi7732** [comment]
Thank you for the contribution!

**Comment by KirkMunroSagent** [comment]
Hi @xiaomi7732,

I just noticed today that last week, on February 19th, the Microsoft.ApplicationInsights.AspNetCore package was updated with a 2.23.0 release, and the 2.22.0 release was immediately marked as deprecated, repeating the issue for which this ticket was originally opened but on a different package.

Would you please suggest internally that the process that was updated for Microsoft.ApplicationInsights.Profiler.AspNetCore be applied more broadly to all Microsoft.ApplicationInsights.* packages?

Thank you!

**Comment by xiaomi7732** [comment]
@KirkMunroSagent Thanks for the suggestion. @TimothyMothra This is feedback **not** to deprecating packages too soon. Do you know the best person to have a discussion with about? Thank you!

**Comment by TimothyMothra** [comment]
Hi @xiaomi7732, you can start a thread with me and my manager (Raj).

> The challenge is that when you mark the previous version of Microsoft.ApplicationInsights.Profiler.AspNetCore as deprecated, it causes a little warning sign to appear in the NuGet Package Manager UI in Visual Studio

I can provide some context, this is the exact behavior that my team wants for these packages. Several years ago we were having challenges with the volume of support cases from users who would go years without updating. We want to surface these warnings to users both in the Visual Studio UI and well as compile time warnings that these older versions are encourage our users to take action.

This policy is also posted on the Readme in our repo: 
> Customers are encouraged to use the latest stable version as that is the version that will get fixes and updates. Beta packages are not recommended for use in production & support is limited. Upon release of the new stable version, the old Beta packages will be unlisted & the old minor version will be marked as deprecated.
https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/Readme.md

**Comment by xiaomi7732** [comment]
Thanks @TimothyMothra for the info.

I am curious, @KirkMunroSagent if the packages would not be marked deprecated, how do you get notice the exitance of the new package? What is your strategy? I think I am trying to figure out, how different, in reality, that you find out the package being deprecated today vs 45 days later?
In other words, what benefits will those 45 days give us?

**Comment by KirkMunroSagent** [comment]
@xiaomi7732 I just came to this repo to search for another issue, and then stumbled upon your question that I never came back to answer. My apologies for that.

New package discovery comes from using the Nuget Package Manager in Visual Studio or from command-line tools such as dotnet outdated that help achieve the same purpose. Packages are updated all the time. Microsoft has "patch Tuesday", a process they put in place many, many years ago where they release package updates on Tuesdays. This is a common practice. There is no need for any package that comes out with an update to "notify" users that there is a new version. It is the responsibility of the developer and their team to update their packages to address security issues and also to keep their code current. I understand that many teams do not handle this responsibility well for a number of reasons (no proper process internally, bad experiences with updates at one point or another, etc.), but that doesn't change that it is the team responsibility to update packages over time. That is what we do internally with my team...we have a standard process that we follow every release (almost monthly with some shift around holidays that make it not quite monthly), where we update all packages in all projects.

By using deprecation as a way to notify users of a package in a system that does not have notifications, well, that's a hack. Deprecation is one thing. Notifications are another thing. If something is deprecated, that indicates to a dev responsible for package management that they are behind and should act to update and eliminate the deprecated packages. It's more a more serious event than "hey, we have a new updated version that we'd like you to use".

Xiaomi: If every product team deprecated old versions of their packages the moment that they came out with new versions because they wanted to notify users of those versions, what would happen? Can you imagine the chaotic effect that would have on package management? It would be absolutely terrible, because you no longer would have a way to identify distinguish between real issues that are pressing, such as when a package is deprecated due to a published security vulnerability where someone may want to do a package update out of band from their usual package management process, and "notifications" disguised as deprecated packages. In my opinion/experience, deprecation should not be used for this purpose, period.

> In other words, what benefits will those 45 days give us?

45 days allows normal package management to occur, so that dev teams that have a proper package management process in place can go about their work, knowing that when something comes up flagged as deprecated, it is something they should pay attention to out-of-band, vs. just some noisy team that decides that their package updates are important enough to interrupt the normal flow of a well-designed package management process.

**Comment by xiaomi7732** [comment]
Thank you @KirkMunroSagent for sharing. It has always been fascinating to learn how various engineering groups handling these challenges and talking about the reasons behind.
