### ISSUE TITLE
"Profile now" from portal should work for dockerized applications

### ISSUE THREAD

**Issue by bremnes** [microsoft/ApplicationInsights-Profiler-AspNetCore#22]
Following the tutorials I've been able to run AI profiling on a dockerized asp.net core application (asp.net core running on linux docker locally at the moment).

I see the server registered in AI; live metrics streaming in the "live metrics stream" and requests/error/dependencies showing up as they should. For the profiler I see that it profiles two minutes at startup and then idle for 58 minutes before another profiling session. This all works as expected.

But the `profile now` button doesn't seem to work. And this is what could make it a killer feature in my book. We've got several applications/micro services talking together and they have the AI instance in common. So if we could say `profile now` and gather metrics/debug data across them that would be golden.

If it's already supported and I've missed some configuration, please let me know and I'll kill this issue. I looked around but couldn't seem to find anything pinpointing this use case.

**Comment by pharring** [comment]
@xiaomi7732 comments?

**Comment by xiaomi7732** [comment]
@bremnes Thanks for the asking. It is an interesting question.
There are at least 2 benefits for `Profile Now`:

1. One can start the profiling at the time on demand;
2. One can align the profiling across multiple services at the same time;

Could you please tell me which one do you think will benefit you more at this stage?

The reason I ask is that it might take a while before we can implement `Profile Now`. However, there might be something that we can reach easliy without `Profile Now`.

For example, if you want to align the profiling across multiple services, one simple solution could be:
* Allow sets app settings / config / environment to pick a start time. Once the start time is aligned across the services, the profiling will always be aligned.

**Comment by bremnes** [comment]
@xiaomi7732, both to be honest. Ideally one should be able to profile one/several/all connected services/applications regardless of them running in Kubernetes, Azure or on a VM in your own data center.

From the documentation on [app insights profiler](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/application-insights/app-insights-profiler.md#-manually-trigger-profiler) it says that it will `trigger profiler on all instances of the linked web apps`. It might be that `web app` in this context is limited to Azure app/web app, but I'd hope not.

For your comment regarding picking a start time, is there any way to easily control that? I've noticed that profiling by default happens in the two first minutes of the process start and then every hour (58 minute) after that. If we can control that, it would be great as well. For instance it's not perfect if a node fails in Kubernetes, and then all the pods who are rescheduled to another server all starts profiling simultaneously. That could break/have impact on the next node as well.

**Comment by andtii** [comment]
One year later do we have any progress on this?

**Comment by xiaomi7732** [comment]
@andtii Thanks for your ask. Do I understand correct by **this**, you mean the **Profile Now**? By current timeline that I have, it will take about one month for a new version to roll-out with the capability. I'll update the date when I have anything concrete.

**Comment by andtii** [comment]
@xiaomi7732 Nicee that sounds awesome
