### ISSUE TITLE
Remove `System.Net.Http` package dependency from `Microsoft.ApplicationInsights.Profiler.Core`.

### ISSUE THREAD

**Issue by teo-tsirpanis** [microsoft/ApplicationInsights-Profiler-AspNetCore#221]
_(repeating an email I sent to the package maintainers via nuget.org)_

Please remove the dependency to the `System.Net.Http` package from the `Microsoft.ApplicationInsights.Profiler.Core` package.

`System.Net.Http` is a legacy package that brings tons of unnecessary transitive dependencies, and should not be referenced. The `HttpClient` class is already built-in to .NET Standard 2.0 so you don't need to change any code. See also https://x.com/isaac_abraham/status/1798331555875893633

You can also remove the package `System.ValueTuple`, but this one does not cause much trouble.

**Comment by xiaomi7732** [comment]
Let me take a look.

**Comment by xiaomi7732** [comment]
Hey @teo-tsirpanis,  It looks like it is a legacy dependency. I have submitted a PR to get rid of it. Expecting the fix in a beta package.

**Comment by teo-tsirpanis** [comment]
Thank you very much!

**Comment by rmihael** [comment]
Hi! What are the plans to release this fix? Vulnerability scanners are triggering on these legacy dependencies.

**Comment by xiaomi7732** [comment]
@rmihael Thanks for the query. The package is in the pipeline. Expect to happen in the next few days unless blocked.

**Comment by xiaomi7732** [comment]
Please check out the package: https://www.nuget.org/packages/Microsoft.ApplicationInsights.Profiler.AspNetCore/2.7.2-beta1

**Comment by teo-tsirpanis** [comment]
Thanks!
