### ISSUE TITLE
Usage with OpenTelemetry?

### ISSUE THREAD

**Issue by thed24** [microsoft/ApplicationInsights-Profiler-AspNetCore#222]
The Azure OpenTelemetry distro claims to support both the profiler and snapshot debugger (see below), however there is no documentation regarding how to configure it to support both features. Could you shed some light on this please? Thanks in advance!

![image](https://github.com/user-attachments/assets/6d8350a0-91fb-4564-98d4-cb9a97309f2e)

**Comment by xiaomi7732** [comment]
Hey @thed24, thanks for the ask.

At this moment, the windows profiler works with Application Insights OpenTelemetry distro (https://learn.microsoft.com/en-us/azure/azure-monitor/profiler/profiler).

There's no support for the EventPipe Profiler (this NuGet).

Please let me know if you have more questions.

**Comment by thed24** [comment]
Thanks for the prompt response! Is any specific configuration required for an App Service running on Linux? Previously, a whole specific NuGet package was required to enable profiling, but now it does not seem to work out of the box. You did mention Windows, does this mean it doesn't work for Linux?

**Comment by xiaomi7732** [comment]
@thed24, I am reading between the lines. Check my understanding, please:

1. Your application is hosted on Linux.
2. You have been using the [Microsoft.ApplicationInsights.Profiler.AspNetCore](https://www.nuget.org/packages/Microsoft.ApplicationInsights.Profiler.AspNetCore) for profiling.
And
3. You are asking: can profiler work if you switch from using application insights to Open Telemetry.

If I understand that correct, at this point, `Microsoft.ApplicationInsights.Profiler.AspNetCore` won't work for that scenario right now.

Please let me know if there's more questions. Thanks.

**Comment by xiaomi7732** [comment]
Hi there, I am sorry, my info about the windows agent supporting OpenTelemetry wasn't accurate. I think there's a document error and its not supported yet. 
There's work going on. I don't have a good ETA at this point.

**Comment by xiaomi7732** [comment]
Hey @dominic-codespoti, now we have a new package under building to support OTel distro on Windows & Linux. Please check #230 out for more details. Thanks.
