### ISSUE TITLE
"InstrumentationKeyInvalidException" when "APPLICATIONINSIGHTS_CONNECTION_STRING" a environment variable

### ISSUE THREAD

**Issue by onionhammer** [microsoft/ApplicationInsights-Profiler-AspNetCore#226]
**Describe the bug**
I'm seeing this exception in my logs with version 2.7.2 and OTEL enabled. Is this package compatible with Azure.Monitor.OpenTelemetry.AspNetCore and Aspire applications?

**Comment by xiaomi7732** [comment]
@onionhammer I'll get back to you.

**Comment by xiaomi7732** [comment]
Hey @onionhammer , that scenario should work. Here's a quick try on my box.
I tried setup the environment variable of `APPLICATIONINSIGHTS_CONNECTION_STRING` and it is picked up properly by the profiler.

```shell
PS C:\Demo\ProfilerWithConnectionString> $env:APPLICATIONINSIGHTS_CONNECTION_STRING='InstrumentationKey=my-instrumentation-key-guid;IngestionEndpoint=https://westus3-1.in.applicationinsights.azure.com/;ApplicationId=redacted'
PS C:\Demo\ProfilerWithConnectionString> dotnet run
Building...
info: Microsoft.ApplicationInsights.Profiler.Core.IServiceProfilerContext[0]
      Profiler Endpoint: https://profiler.monitor.azure.com/
info: Microsoft.ApplicationInsights.Profiler.Core.TraceScavenger.TraceScavengerService[0]
      TraceScavengerService started. Initial delay: 00:00:00, Grace period from last access: 00:10:00
info: Microsoft.ApplicationInsights.Profiler.AspNetCore.ServiceProfilerAgentBootstrap[0]
      Starting application insights profiler with instrumentation key: my-instrumentation-key-guid
info: Microsoft.ApplicationInsights.Profiler.Core.TraceScavenger.TraceScavengerListener[0]
      File scavenger started.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5214
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Demo\ProfilerWithConnectionString
info: Microsoft.ApplicationInsights.Profiler.Core.ServiceProfilerProvider[0]
      Service Profiler session started.
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
```

When the exception is thrown, what's in the exception message? That might help figure out what exactly was the issue. Also, shooting blindly a bit, was it running on Linux? If so, try use double underscore than the single ones for the variable name. For example, use `APPLICATIONINSIGHTS__CONNECTION__STRING` instead.

**Comment by onionhammer** [comment]
Hi @xiaomi7732 

I'm just running this on Windows, with Aspire which loads in the environment variable, "APPLICATIONINSIGHTS_CONNECTION_STRING". I could try deploying it to Linux.

Aspire adds App Insights with the `AzureApplicationInsightsExtensions`

```C#

// Add Application Insights
var appInsights = builder.AddAzureApplicationInsights("insights");

var api = builder.AddProject<YourProject>("api").WithReference(appInsights); // APPLICATIONINSIGHTS_CONNECTION_STRING is now added when you run your aspire project
```

**Comment by onionhammer** [comment]
Update: I can't reproduce the issue above, if I put the `AddApplicationInsightsTelemetry` and `AddServiceProfiler` before Aspire's conventional `AddServiceDefaults`, it works, if after it crashes with different errors.

**Comment by xiaomi7732** [comment]
Okay. Thanks for the update @onionhammer . Feel free to file other issues if you need help troubleshooting those other errors.
