### ISSUE TITLE
PublishSingleFile causes `ArgumentNullException` from `UploaderLocatorByUnzipping.GetUploaderFullPath`

### ISSUE THREAD

**Issue by bgrainger** [microsoft/ApplicationInsights-Profiler-AspNetCore#228]
**Describe the bug**

When a .NET application is published using the `PublishSingleFile` MSBuild property (via the project file or via `dotnet publish -p:PublishSingleFile=true`), `UploaderLocatorByUnzipping` crashes with an `ArgumentNullException`.

**To Reproduce**

1. Clone the EnableServiceProfilerForContainerAppNet6 example.
2. In `appsettings.json`, specify a valid instrumentation key.
3. Update the .NET Framework in the csproj file: `<TargetFramework>net8.0</TargetFramework>`. Update Microsoft.ApplicationInsights.Profiler.AspNetCore to 2.7.2.
4. Publish a Docker container using the SDK: `dotnet publish --os linux --arch x64 /t:PublishContainer`
5. Run the Docker container: `docker run -p 8080:8080 enableserviceprofilerforcontainerappnet6:latest`
6. Everything should run correctly. Stop the container.
7. Now add the following to the `<PropertyGroup>` in the csproj: `<PublishSingleFile>true</PublishSingleFile>`
8. Repeat steps 4 and 5.
9. Access http://localhost:8080/weatherforecast
10. Wait two minutes

The following exception is logged:

```
fail: Microsoft.ApplicationInsights.Profiler.Core.ServiceProfilerProvider[0]
      Unexpected error happens on stopping service profiler.
      System.ArgumentNullException: Value cannot be null. (Parameter 'path')
         at System.ArgumentNullException.Throw(String paramName)
         at System.IO.DirectoryInfo..ctor(String path)
         at Microsoft.ApplicationInsights.Profiler.Core.Utilities.ProfilerCoreAssemblyInfo.get_Directory()
         at Microsoft.ApplicationInsights.Profiler.Core.UploaderProxy.UploaderLocatorByUnzipping.GetUploaderFullPath()
         at Microsoft.ApplicationInsights.Profiler.Core.UploaderProxy.UploadLocatorBase.Locate()
         at Microsoft.ApplicationInsights.Profiler.Core.UploaderProxy.UploaderPathProvider.GetUploaderFullPath()
         at Microsoft.ApplicationInsights.Profiler.Core.UploaderProxy.UploaderPathProvider.TryGetUploaderFullPath(String& uploaderFullPath)
         at Microsoft.ApplicationInsights.Profiler.Core.ServiceProfilerProvider.PostStopProcessAsync(PostStopOptions e, CancellationToken cancellationToken)
```

**Expected behavior**

Uploading should work even if the application is published as a single file. `TraceUpload.zip` is still present in the `/app` directory in the container image. Maybe `ProfilerCoreAssemblyInfo` could look for the location of the executing assembly, not look for a specific assembly on disk?

**Desktop (please complete the following information):**
 - OS: Windows 10, but running a Linux container
 - Package version (Microsoft.ApplicationInsights.Profiler.AspNetCore): 2.7.2
 - Application Insights: 4d7bacd5-388f-4d22-ac8e-XXX

**Additional context**

**Comment by xiaomi7732** [comment]
This is interesting. Following the callstack, the exception is actually thrown here:

```csharp
    class ProfilerCoreAssemblyInfo
    {
        public DirectoryInfo Directory => new DirectoryInfo(Path.GetDirectoryName(_thisAssembly.Value.Location));
        ...
    }
```

That means, `Path.GetDirectoryName()` is returning null, and that probably is because `_thisAssembly.Value.Location` is null.
`_thisAssembly` is a lazy of Assembly, using `typeof(ProfilerCoreAssemblyInfo).Assembly`.

Is that `null` because the profiler assembly doesn't exist under the single file deployment? 🤔

**Comment by pharring** [comment]
@xiaomi7732 see https://learn.microsoft.com/dotnet/core/deploying/single-file/overview?tabs=cli#api-incompatibility

You'll need to find another way. Probably `AppContext.BaseDirectory`.

**Comment by xiaomi7732** [comment]
> [@xiaomi7732](https://github.com/xiaomi7732) see https://learn.microsoft.com/dotnet/core/deploying/single-file/overview?tabs=cli#api-incompatibility
> 
> You'll need to find another way. Probably `AppContext.BaseDirectory`.

Sound like fun.

**Comment by xiaomi7732** [comment]
@bgrainger I looked into the issue. Once we get pass the point of returning the path properly, there reveals the real issue that the .NET runtime is not there for the uploader to start and the uploading will fail.

Basically, the current design doesn't work very well for applications that packed with the .NET runtime. It is that way for the uploader to share the .NET runtime without staying in the same process of your application.

Could you please help me understand what is the reason you choose to deploy your application as `SingleFile`?

**Comment by bgrainger** [comment]
> Could you please help me understand what is the reason you choose to deploy your application as SingleFile?

I initially published as SingleFile (and as self-contained, per the other issue) to get the smallest possible container image. However (partly due to Application Profiler and partly due to just reconsidering the options) I've switched to non-single-file, non-self-contained to benefit from reusing as many base layers as possible.

> It is that way for the uploader to share the .NET runtime without staying in the same process of your application.

We're not experimenting much with AOT yet, but it seems like .NET is moving in that direction and the uploader might need to consider an in-proc model that doesn't require external dependencies (even the .NET runtime)?

FWIW, this particular issue is no longer a blocking problem for us, so feel free to close it if you don't think you'll fix it (due to Application Insights Profiler's design)

**Comment by xiaomi7732** [comment]
Hey @bgrainger , thanks for the feedback. This is an important data point what our users are using or intend to use.
We actually are looking into some re-architecture of our implementation to properly address the issue.

Just for your information, in-proc uploader was an option, it's too much an overhead for the user's app and we pulled it out on purpose. We shall revisit the tradeoffs, but I don't see it too feasible, TBH.
Another idea is to have the uploader run in another container (sidecar). That is still in early stage, and we have some tech hurtles that we are looking into.

I'll close this issue for now, mainly because we are not going to address this issue on its own. Feel free to file new issues when there's other problems.
