### ISSUE TITLE
For Windows as well as linux?

### ISSUE THREAD

**Issue by AlexKeySmith** [Microsoft/ApplicationInsights-Profiler-AspNetCore#35]
Hi,

In the home readme it states: "App Services **Linux** profiler"

However deeper in the documentation: "https://github.com/Microsoft/ApplicationInsights-Profiler-AspNetCore/blob/master/examples/EnableServiceProfilerInVSCLR2_2_Win/README.md"

It also indicates Windows.

For Application Insights Profiler 1.1.4-beta1 and above, profiling on **Windows** is supported as an experimental feature for ASP.NET Core 2.2 and above applications.

I've never had any luck enabling the profiler via the traditional way in the portal (https://docs.microsoft.com/en-us/azure/azure-monitor/app/profiler) - a separate issue for another thread..... So hoping to give this nuget package a shot?

**Comment by pharring** [comment]
It's still experimental, but ready for testing and we'd welcome feedback.

BTW, this was part of the plan all along. The traditional profiler is based on ETW, which is a Windows-only technology. So we needed to develop a new solution for profiling .NET Core applications on Linux. The Bing team created an in-proc profiler called BPerf for CoreCLR (https://github.com/Microsoft/BPerf) and we took that idea and turned it into a supported feature for .NET Core 2.0. Having had a couple of versions to work out the early kinks, we feel it's ready to try it out for Windows too.

**Comment by AlexKeySmith** [comment]
Thanks for the quick response and very cool I look forward to playing with it.

Is this also something recommended over the runtime extension? i.e in the past we've needed the SDK and runtime extension to get the best of both worlds... not necessarily in regards to the profiler, so perhaps this is secondary question is better of suited in the other app insights github repos.

**Comment by pharring** [comment]
For now, don't install the runtime extension. It's unaware of this method of profiling and will probably mess things up pretty horribly. Stick with the SDK.

**Comment by AlexKeySmith** [comment]
No worries, thanks for the great advice.
