### ISSUE TITLE
Adding profiler to dotCore 2.1 on linux (AKS) causes huge memory usage.

### ISSUE THREAD

**Issue by bhbeebe** [Microsoft/ApplicationInsights-Profiler-AspNetCore#40]
We have added the profiler to our project.  We are using dotNet Core on linux (Ubuntu) within kubernetes.  Without Application Insights profiler, our application sits between 200m and 512m.  When we add the profiler.  We see it immediately jump up to 1.2 GB and then it keeps climbing settling in around 7.5 GB to 8 GB per pod.  We have used both workstation and server GC.  Workstation tends to increase memory slower.

**Comment by xiaomi7732** [comment]
@bhbeebe I am sorry that happens. Please provide some more info around this:
1. What is the package version of the App Insights Profiler are you using?
2. What's the configuration of the service profiler? (Refer [Configuration](https://github.com/Microsoft/ApplicationInsights-Profiler-AspNetCore/blob/master/Configurations.md)) to tweak the memory size?
3. Is there any other logging library are you using?

Thanks!

**Comment by bhbeebe** [comment]
We have confirmed that using 2.2 has resolved the big memory issues.  We are using the AppInsights +  the profiler without issues so far.  The profile does provide the additional stack traces that provide us further insights into issues within the code.

**Comment by xiaomi7732** [comment]
@bhbeebe Thanks for the feedback.
