### ISSUE TITLE
profiler is not cleaning up netperf files

### ISSUE THREAD

**Issue by bhbeebe** [Microsoft/ApplicationInsights-Profiler-AspNetCore#42]
We are seeing our /tmp directory increasing in size due to the netperf files; upto 3.8GB.  It looks like the profiler is not cleaning up these files after upload.  

According to the docs it looks like expected behavior is for these to be deleted after upload.

This is what the current /tmp looks like.

3.8G	./tmp/

drwxr-xr-x 4 root root 4096 Apr 13 10:04 0f5q0aim.m21
drwxr-xr-x 4 root root 4096 Apr 13 23:06 0v2bc13i.3ej
drwxr-xr-x 4 root root 4096 Apr 13 05:03 0y4kwp0h.2fm
drwxr-xr-x 4 root root 4096 Apr 15 15:12 11zy22hc.ldk
drwxr-xr-x 4 root root 4096 Apr 15 10:11 1xe4gp4p.ydd
drwxr-xr-x 4 root root 4096 Apr 12 22:02 2arqpmha.3jb
drwxr-xr-x 4 root root 4096 Apr 15 02:10 2zipqmio.z2q
drwxr-xr-x 4 root root 4096 Apr 13 03:03 35kscfzn.r2z
drwxr-xr-x 4 root root 4096 Apr 15 16:12 3i0vpefx.zxp
drwxr-xr-x 4 root root 4096 Apr 12 19:02 4d2acvr5.ldb
drwxr-xr-x 4 root root 4096 Apr 12 21:02 4fn2nl13.tx1
drwxr-xr-x 4 root root 4096 Apr 13 08:04 4qi5rk5u.cqy
drwxr-xr-x 4 root root 4096 Apr 15 08:11 4rlsctm1.nkq
drwxr-xr-x 4 root root 4096 Apr 14 02:06 5mhqgmci.cr2
drwxr-xr-x 4 root root 4096 Apr 12 23:02 5mjdvl25.pju
drwxr-xr-x 4 root root 4096 Apr 13 12:04 5plcall3.qyg
drwxr-xr-x 4 root root 4096 Apr 14 19:09 a3bstomk.2yv
drwxr-xr-x 4 root root 4096 Apr 12 16:01 a4nefdbe.twk
drwxr-xr-x 4 root root 4096 Apr 15 11:11 arlebobb.bzo
drwxr-xr-x 4 root root 4096 Apr 15 09:11 b5svqnpp.4xn
drwxr-xr-x 4 root root 4096 Apr 15 04:10 bs4nar3f.40l
drwxr-xr-x 4 root root 4096 Apr 14 23:09 cap0kzpu.y41
drwxr-xr-x 4 root root 4096 Apr 14 06:07 cfl3nmff.xoj
drwxr-xr-x 4 root root 4096 Apr 15 05:10 civu3vnq.q1t
prwx------ 1 root root    0 Apr 12 13:59 clr-debug-pipe-1-684823511-in
prwx------ 1 root root    0 Apr 12 13:59 clr-debug-pipe-1-684823511-out
drwxr-xr-x 4 root root 4096 Apr 14 17:09 d5ssnagd.3wc
drwxr-xr-x 4 root root 4096 Apr 13 18:05 dkhr2ywv.q4q
drwxr-xr-x 4 root root 4096 Apr 15 14:12 duv3vvtv.tdw
drwxr-xr-x 4 root root 4096 Apr 13 04:03 eyt4ui2h.poo
drwxr-xr-x 4 root root 4096 Apr 14 21:09 fwoypt0e.w03
drwxr-xr-x 4 root root 4096 Apr 14 16:08 gemz0fre.ehu
drwxr-xr-x 4 root root 4096 Apr 14 15:08 ghepdpsd.51g
drwxr-xr-x 4 root root 4096 Apr 12 15:01 giskwfxc.zea
drwxr-xr-x 4 root root 4096 Apr 14 08:07 hbzsctic.i41
drwxr-xr-x 4 root root 4096 Apr 13 11:04 hdhg1c3z.qlw
drwxr-xr-x 4 root root 4096 Apr 13 15:05 hgkuuwv5.wm3
drwxr-xr-x 4 root root 4096 Apr 14 20:09 housrtei.smt
drwxr-xr-x 4 root root 4096 Apr 13 21:06 hw5kf0rf.snr
drwxr-xr-x 4 root root 4096 Apr 12 17:01 icbhpjwh.qrb
drwxr-xr-x 4 root root 4096 Apr 12 18:02 icibf1b2.qvo
drwxr-xr-x 4 root root 4096 Apr 14 03:07 jcgi0xwl.rme
drwxr-xr-x 4 root root 4096 Apr 15 13:12 jmuwxmvf.rjb
drwxr-xr-x 4 root root 4096 Apr 14 07:07 jnctro4r.qvc
drwxr-xr-x 4 root root 4096 Apr 13 14:05 jtzvsese.hrx
drwxr-xr-x 4 root root 4096 Apr 13 06:03 jyyszxdi.4al
drwxr-xr-x 4 root root 4096 Apr 14 12:08 k4vgr5wk.l34
drwxr-xr-x 4 root root 4096 Apr 14 18:09 kmlcgbpb.x4c
drwxr-xr-x 4 root root 4096 Apr 13 19:05 kvu4buul.q1k
drwxr-xr-x 4 root root 4096 Apr 13 16:05 l4i1rqy2.gsj
drwxr-xr-x 4 root root 4096 Apr 13 13:04 maugkj3e.4pn
drwxr-xr-x 4 root root 4096 Apr 13 17:05 ndzhnn51.kr4
drwxr-xr-x 4 root root 4096 Apr 14 22:09 nv0gp2w2.c02
drwxr-xr-x 4 root root 4096 Apr 15 01:10 nx0upoqe.nyx
drwxr-xr-x 4 root root 4096 Apr 13 02:03 nz0dgb1r.oqh
drwxr-xr-x 4 root root 4096 Apr 15 03:10 nzgb4s4p.ied
drwxr-xr-x 4 root root 4096 Apr 14 00:06 olqbnj2x.xei
drwxr-xr-x 4 root root 4096 Apr 14 09:07 pgewy3ze.yhl
drwxr-xr-x 4 root root 4096 Apr 12 14:01 q5nupwna.kgx
drwxr-xr-x 4 root root 4096 Apr 13 22:06 qn2cxfog.5ph
drwxr-xr-x 4 root root 4096 Apr 13 20:05 qw1m0cfv.pvn
drwxr-xr-x 4 root root 4096 Apr 15 12:11 ryzf0kgp.hvc
drwxr-xr-x 4 root root 4096 Apr 15 07:11 s3a0n3dh.fu0
drwxr-xr-x 4 root root 4096 Apr 15 06:10 s3sjyvpo.ok4
drwxr-xr-x 4 root root 4096 Apr 15 17:12 sgse4xjj.tlj
drwxr-xr-x 4 root root 4096 Apr 13 07:04 sp3og1qo.s1m
drwxr-xr-x 4 root root 4096 Apr 13 00:02 stjwctcj.h1p
drwxr-xr-x 4 root root 4096 Apr 14 13:08 ui1eafxp.irs
drwxr-xr-x 4 root root 4096 Apr 14 14:08 v0idmuvv.xjf
drwxr-xr-x 4 root root 4096 Apr 14 04:07 w0ilwlbj.eza
drwxr-xr-x 4 root root 4096 Apr 14 11:08 w3q4wsrd.4u0
drwxr-xr-x 4 root root 4096 Apr 13 09:04 wzvmb2r3.beg
drwxr-xr-x 4 root root 4096 Apr 13 01:03 x2aqlqje.cjp
drwxr-xr-x 4 root root 4096 Apr 14 01:06 x2i0jspo.opu
drwxr-xr-x 4 root root 4096 Apr 14 10:08 y0e0ca4h.3vq
drwxr-xr-x 4 root root 4096 Apr 14 05:07 yhfvz4vr.df5
drwxr-xr-x 4 root root 4096 Apr 12 20:02 z1hqtkw2.3wv
drwxr-xr-x 4 root root 4096 Apr 15 00:10 zkxwrkrg.k5q

**Comment by xiaomi7732** [comment]
Thanks for the report. I'll take a look.

**Comment by xiaomi7732** [comment]
Looks like a bug in Profiler. I'll come up with a fix.

**Comment by xiaomi7732** [comment]
This issue has been fixed and will be released alone with other changes in the next release. Expecting version number: 1.1.6-*

**Comment by xiaomi7732** [comment]
Find the package here: https://www.nuget.org/packages/Microsoft.ApplicationInsights.Profiler.AspNetCore/1.1.6-beta1
