### ISSUE TITLE
What about Mac support?

### ISSUE THREAD

**Issue by scotthellewell** [microsoft/ApplicationInsights-Profiler-AspNetCore#44]
I was attempting to try this out on my .net core 2.2 asp.net application.  I am currently running it on a Mac for development and then pushing it to Azure app services running on linux.  When testing on the Mac, the program crashes before it fully starts up. I see the charts show what versions work with linux and what versions work with Windows.  What is the recommendation for Mac?

**Comment by xiaomi7732** [comment]
Hi @scotthellewell Profiler for Mac is not officially supported.
When you have crash on the Mac, what is the callstack look like?

**Comment by xiaomi7732** [comment]
Close this since there's no response for a while.
