### ISSUE TITLE
Is ApplicationInsights Profiler open source?

### ISSUE THREAD

**Issue by tremblaysimon** [microsoft/ApplicationInsights-Profiler-AspNetCore#45]
That repository contains examples and documentation, but not the ApplicationInsights Profiler source code. Is ApplicationInsights profiler open source?

**Comment by xiaomi7732** [comment]
@tremblaysimon Thanks for the asking. ApplicationInsights Profiler is not open sourced. 
Just out of curiosity, is there anything specific you are looking for?
