### ISSUE TITLE
No customer events released error ASP.NET Core 3

### ISSUE THREAD

**Issue by isaac2004** [microsoft/ApplicationInsights-Profiler-AspNetCore#47]
I tried to follow the instructions for an ASP.NET Core 3.0 App, and I get the following error

> fail: ServiceProfiler.EventPipe.Client.ServiceProfilerProvider[0]
>      Expected trace validation error.
> ServiceProfiler.EventPipe.Client.TraceValidators.ValidateFailedException: [ActivityListValidator] No sample activity matches the trace.
>   at ServiceProfiler.EventPipe.Client.TraceValidators.ActivityListValidator.ValidateImp(IEnumerable`1 samples)
>   at ServiceProfiler.EventPipe.Client.TraceValidators.TraceValidatorBase.Validate(IEnumerable`1 samples)
>   at ServiceProfiler.EventPipe.Client.TraceValidators.TraceValidatorBase.Validate(IEnumerable`1 samples)
>   at ServiceProfiler.EventPipe.Client.ServiceProfilerProvider.OnTraceStopped(Object sender, TraceStopEventArgs e)
> warn: ServiceProfiler.EventPipe.Client.ServiceProfilerProvider[0]
>      Trace validation failed. No customer events released.

Is there an additional step other than turn off the compat test?

**Comment by xiaomi7732** [comment]
@isaac2004, thanks for filing the issue. I can repro what you mentioned on the .NET Core 3.0.100 and I have some direction to look into. It will take sometime. I'll get back to you once there progress.

**Comment by xiaomi7732** [comment]
@isaac2004, please try this again with [1.1.7-beta2](https://www.nuget.org/packages/Microsoft.ApplicationInsights.Profiler.AspNetCore/1.1.7-beta2).

**Comment by xiaomi7732** [comment]
Cross reference #48 , this issue has been fixed. Close this one.
