### ISSUE TITLE
Worker Service applications (non-HTTP applications) support

### ISSUE THREAD

**Issue by luca-esse** [microsoft/ApplicationInsights-Profiler-AspNetCore#49]
Hi,

Are there any plans to support worker service applications much like it was done with the [Microsoft.ApplicationInsights.WorkerService](https://www.nuget.org/packages/Microsoft.ApplicationInsights.WorkerService) package?

**Comment by xiaomi7732** [comment]
@luca-esse Thanks for your feedback. Supporting work services application is not on our radar at this point. The application insights profiler currently is built around the `Requests telemetries`, which is not an native member of work services apps.

That said, if you are running on a .NET Core 3.0 and above, and if your goal is trying to get a profiling trace for those apps and you are comfortable with perfview for analysis, please consider:
* [DotNet Trace](https://github.com/dotnet/diagnostics/blob/master/documentation/dotnet-trace-instructions.md) from the repo of [dotnet/diagnostics](https://github.com/dotnet/diagnostics).

Personally, I also am building a wrap on top of the trace tool [in this fork](https://github.com/xiaomi7732/diagnostics).

Also, we will announce it here if the plan changes.

Again thanks for your help.
