### ISSUE TITLE
Hosting Startup is not working in dotnet core 3.0 Azure App Service (System.MissingMethodException: Method not found)

### ISSUE THREAD

**Issue by valeriob** [microsoft/ApplicationInsights-Profiler-AspNetCore#52]
Hi,
i'm using the Microsoft.ApplicationInsights.Profiler.AspNetCore 2.0.0-beta1 in azure App Service with configured runtime netcore 3.0 and the following environment variable 
ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=Microsoft.ApplicationInsights.Profiler.AspNetCore
It fails with this exception : 

> 2019-10-25T15:09:06.749908649Z Unhandled exception. System.MissingMethodException: Method not found: 'Microsoft.AspNetCore.Hosting.IHostingEnvironment Microsoft.AspNetCore.Hosting.WebHostBuilderContext.get_HostingEnvironment()'.
2019-10-25T15:09:06.749966649Z    at Microsoft.AspNetCore.Hosting.ServiceProfilerInjection.<>c.<Configure>b__0_0(WebHostBuilderContext hostingContext, IConfigurationBuilder config)
2019-10-25T15:09:06.749973349Z    at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
2019-10-25T15:09:06.749978149Z    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
2019-10-25T15:09:06.756355094Z    at MyApp.Program.Main(String[] args) in C:\BuildAgent\work\bfbade9ea212e645\MyApp\Program.cs:line 14

Everything works fine if i disable it (by removing the env variable above).
Thanks

**Comment by xiaomi7732** [comment]
@valeriob, Thanks for your report. Hosting startup is not supported in 2.0.0-beta1. Please follow the example of [Quick Start](https://github.com/microsoft/ApplicationInsights-Profiler-AspNetCore/tree/master/examples/QuickStart3_0) to enable Profiler.

Also, could you please tell us what is the reason for you to choose to use hosting startup? It will help us decide what's the next priority.

Thanks!

**Comment by valeriob** [comment]
I like it because it's automatically enabled via env variable on production environment, so it will not run during development, and it's non invasive, can be enabled/disabled in prod without code deploy.

**Comment by xiaomi7732** [comment]
Thanks @valeriob for your feedback. Just in case you don't know, this following environment variable can be used as a kill switch of the profiler:

> ServiceProfiler__Duration

Check out the documentation: [Configuration References](https://github.com/microsoft/ApplicationInsights-Profiler-AspNetCore/blob/master/Configurations.md#configuration-references).

**Comment by valeriob** [comment]
I'm trying 2.0.0-beta2, but it does not work with dotnet core 3.0, i get this error during startup : 

System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Diagnostics.PerformanceCounter, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.'

**Comment by xiaomi7732** [comment]
@valeriob That is interesting. Let's troubleshoot.
I assume the application failed to start at all, right? Are you running it on Windows or Linux? Could you please run `dotnet --info` and past the output here?

**Comment by valeriob** [comment]
Hi,
i created a brand new aspnet core 3.0 application, added the nuget package, those 2 lines in configure services
          services.AddApplicationInsightsTelemetry(); // Enable Application Insights telemetry
            services.AddServiceProfiler(); // Add this line of code to Enable Profiler
and this code in the appsettings.json:
  "ApplicationInsights": {
    "InstrumentationKey": "replace-with-your-instrumentation-key"
  }
i get this that exception.

dotnet --info : 
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by xiaomi7732** [comment]
@valeriob, so, you are running it locally on your box, right? I ran it in the same environment and didn't have a problem. If possible, could you please run your app as administrator and give it another shoot? Let's see if that is due to permission issue before we try the fancy [**fuslogvw**](https://docs.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer).

**Comment by valeriob** [comment]
Yes, i never run as admin.
But i can reproduce it on many machines, in vs F5 both admin and normal user.

**Comment by xiaomi7732** [comment]
By 'vs', I think you mean Visual Studio? Could you please share the version number for VS?

To sort out visual studio magics, in the project folder, run:
```
dotnet run
```
Does it work?

Also, could you please paste your project file(*.csproj), just want to see project references and that may help us repro the issue here.

**Comment by valeriob** [comment]
Yes, visual studio 16.3.6, and it does not work with dot net run eather.

**Comment by xiaomi7732** [comment]
@valeriob I tried the same steps in VS 16.3.6 and it worked for me. There must be something I missed. Let me share my project and you can compare it with yours. At the same time, if you will to, share the project with me and I can take a look at it for you as well.

[WebApplication.zip](https://github.com/microsoft/ApplicationInsights-Profiler-AspNetCore/files/3832801/WebApplication.zip)

**Comment by valeriob** [comment]
Hi xiaomi,
i saw that you added the guide for .netcore 3 exactly after i opened the issue. i diagnosed the problem, and it's due to the dependency required for Microsoft.ApplicationInsights.AspNetCore must be at least 2.8+, while the nuget package requires only Microsoft.ApplicationInsights.AspNetCore (>= 2.3.0).

I suggest to upgrade the nuget package to reflect the real version dependency.
Thanks
Valerio

**Comment by xiaomi7732** [comment]
@valeriob Oh~ that is why. I'll look into how to get that fixed.

**Comment by xiaomi7732** [comment]
Hey @valeriob, just FYI, the hosting startup for .NET Core 3.x is coming soon in version 2.1.0-*.

**Comment by valeriob** [comment]
Thanks! i'll keep an eye on that !
