### ISSUE TITLE
Could not get instance for TraceUploaderProxy when using StructureMap as DI container

### ISSUE THREAD

**Issue by cothman** [microsoft/ApplicationInsights-Profiler-AspNetCore#62]
I followed the steps as described in the ReadMe. But it seems that when trying to instantiate classes from Application insights profiler (using `services.AddServiceProfiler()`), StructureMap throws an exception when trying to instantiate TraceUploaderProxy.
Bellow the exception I get: 

`Unable to create a build plan for concrete type Func<String, String, Task<Int32>>
new Func<String, String, Task<Int32>>(Object, IntPtr method)
Object = **Default**
 IntPtr method = Required primitive dependency is not explicitly defined
1.) Attempting to create a BuildPlan for Instance of Func<String, String, Task<Int32>> -- Func<String, String, Task<Int32>>
2.) new TraceUploaderProxy(*Default of IUploaderLocator*, *Default of IProfilerFrontendClient*, *Default of IFileWrapper*, *Default of IOutOfProcCaller*, *Default of IServiceProfilerContext*, *Default of ILogger<TraceUploaderProxy>*, *Default of IOptions<UserConfiguration>*, *Default of Func<String, String, Task<Int32>>*, *Default of Func<String>*)
3.) ServiceProfiler.EventPipe.Client.TraceUploader.TraceUploaderProxy
4.) Instance of ServiceProfiler.EventPipe.Client.TraceUploader.ITraceUploader (ServiceProfiler.EventPipe.Client.TraceUploader.TraceUploaderProxy)
5.) new ServiceProfilerProvider(*Default of TraceConfiguration*, *Default of IServiceProfilerContext*, *Default of ITraceControl*, *Default of ITraceSessionListenerFactory*, *Default of ITelemetryTrackerFactory*, *Default of ICustomEventsTracker*, *Default of ITraceUploader*, *Default of ITraceValidatorFactory*, *Default of IMetadataWriter*, *Default of IOptions<UserConfiguration>*, *Default of IAppInsightsSinks*, *Default of ILogger<ServiceProfilerProvider>*)
6.) ServiceProfiler.EventPipe.Client.ServiceProfilerProvider
7.) Instance of ServiceProfiler.EventPipe.Client.IServiceProfilerProvider (ServiceProfiler.EventPipe.Client.ServiceProfilerProvider)
8.) new OrchestratorEventPipe(*Default of IServiceProfilerProvider*, *Default of IOptions<UserConfiguration>*, *Default of IEnumerable<SchedulingPolicy>*, *Default of IDelaySource*, *Default of ILogger<OrchestratorEventPipe>*)
9.) Microsoft.ServiceProfiler.EventPipe.Orchestration.OrchestratorEventPipe
10.) Instance of Microsoft.ServiceProfiler.Orchestration.IOrchestrator (Microsoft.ServiceProfiler.EventPipe.Orchestration.OrchestratorEventPipe)
11.) new ServiceProfilerStartupFilter(*Default of IOrchestrator*, *Default of IOptions<UserConfiguration>*, *Default of ICompatibilityUtility*, *Default of ILogger<ServiceProfilerStartupFilter>*)
12.) ServiceProfiler.EventPipe.AspNetCore.ServiceProfilerStartupFilter
13.) Instance of Microsoft.AspNetCore.Hosting.IStartupFilter (ServiceProfiler.EventPipe.AspNetCore.ServiceProfilerStartupFilter)
14.) All registered children for IEnumerable<IStartupFilter>
15.) Instance of IEnumerable<IStartupFilter>
16.) new GenericWebHostService(*Default of IOptions<GenericWebHostServiceOptions>*, *Default of IServer*, *Default of ILoggerFactory*, *Default of DiagnosticListener*, *Default of IHttpContextFactory*, *Default of IApplicationBuilderFactory*, *Default of IEnumerable<IStartupFilter>*, *Default of IConfiguration*, *Default of IWebHostEnvironment*)
17.) Microsoft.AspNetCore.Hosting.GenericWebHostService
18.) Instance of Microsoft.Extensions.Hosting.IHostedService (Microsoft.AspNetCore.Hosting.GenericWebHostService)
19.) All registered children for IEnumerable<IHostedService>
20.) Instance of IEnumerable<IHostedService>
21.) Container.GetInstance(IEnumerable<IHostedService>)`

I wanted to force StructureMap to use the default constructor if it exists, but unfortunately I can't, source code isn't available in the repo.

**Comment by xiaomi7732** [comment]
@cothman Sorry to hear that it is not working for you. Could you please provide some information for trouble shooting:
1. What's your dotnet version? (Run `dotnet --info` at the project folder)
2. What is the package version that you referenced to?
3. What's your OS?

Is it possible for you to post a copy of your project here? I can take a look then.

**Comment by cothman** [comment]
@xiaomi7732, this is my dotnet version:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Referencing this packages:

` <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.8.2" /><PackageReference Include="Microsoft.ApplicationInsights.Profiler.AspNetCore" Version="2.0.0-beta4" />
<PackageReference Include="StructureMap.Microsoft.DependencyInjection" Version="2.0.0" />`

And in this repo I reproduce the exception [https://github.com/cothman/AspNetStructureMap](url)

Thank you for the help

**Comment by xiaomi7732** [comment]
@cothman I did some investigation and here's some of my findings:
1. You are trying to use StructureMap to replace the existing DI for the app. However, StructureMap is not working with ASP.NET Core 3.0 yet: Details here: [active issue #47](https://github.com/structuremap/StructureMap.Microsoft.DependencyInjection/issues/47).
1. `ConfigureContainer` will be called only when StructureMap.AspNetCore is referenced due to it's documenation here: [StructureMap GitHub repo](https://github.com/structuremap/StructureMap.Microsoft.DependencyInjection).
That leas to the question: **Is your intention to use `StructureMap.AspNetCore` or `StructureMap.Microsoft.DependencyInjection
`?**
1. StructureMap seems try to injecting services from all referenced assemblies. Since AddServiceProfiler is called already, you shall be able to exclude it from the registry:
    ```
        public void ConfigureContainer(Registry registry)
        {
            registry.Scan(x =>
            {
                x.Exclude(type => type.Name.Contains("ServiceProfiler"));
                x.TheCallingAssembly();
                x.WithDefaultConventions();
                x.LookForRegistries();
            });
        }
    ```
    1. StructureMap, if works, doesn't support to supply null to optional parameters on constructor that is a `Fun<string, string, Task<int>>`, that should be addressed if the filter in the last point is addressed.

----
On the side, it doesn't seem like StrcutureMap is sunsetted. Quoting from its official repro:
> As StructureMap has been **sunsetted**, it's recommended to move to Lamar, StructureMap's successor, which is more compatible with ASP.NET Core's DI system. 

Do you have a specific scenario that structure map is required?

**Comment by cothman** [comment]
@xiaomi7732 Thanks for the reply.
Actually our API uses StructureMap as DI. We are working on a migration to Lamar (it will take some time to implement).
I tried the exculde way in ConfigureContainer, it doesn't seem to be working.

**Comment by xiaomi7732** [comment]
@cothman Thanks for the update. Yes, exclude anything in `ConfigureContainer` will NOT work because it only works with `StructureMap.AspNetCore`. And in your project, `StructureMap.Microsoft.DependencyInjection` is used than `StructureMap.AspNetCore`. At this point, it doesn't matter what you do in `ConfigureContainer` - you can totally remove it and it still won't work.
It seems that you are already start to migrating to Lamar, I would suggest invest time on the new DI and try to make it work there.

**Comment by xiaomi7732** [comment]
Close this as there's nothing actionable from profile perspective. Feel free to open new issues.
