### ISSUE TITLE
Profiler backend service won't handle traces by Application Insights SDK 2.8 and above

### ISSUE THREAD

**Issue by xiaomi7732** [microsoft/ApplicationInsights-Profiler-AspNetCore#68]
When AI.SDK 2.8.x is used, no profiler trace will show in the portal - the client will report is success but you won't be able to see it in the portal.

Workaround:
Disable W3C tracing until the issue in the backend is fixed by adding the code in `Startup.cs`:
```csharp
using System.Diagnostics;
...
// This method gets called by the runtime. Use this method to add services to the container.
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers();

    // Adding the following lines to enable application insights and profiler.
    services.AddApplicationInsightsTelemetry();
    services.AddServiceProfiler();

    // Apply the workaround
    Activity.DefaultIdFormat = ActivityIdFormat.Hierarchical;
    Activity.ForceDefaultIdFormat = true;
...
}
```

Reference:
[Enable W3C distributed tracing support for ASP.NET Core apps](https://docs.microsoft.com/en-us/azure/azure-monitor/app/correlation#enable-w3c-distributed-tracing-support-for-aspnet-core-apps).

**Comment by johnrom** [comment]
Running into this problem with a Windows App as well. None of the documentation references `services.AddServiceProfiler()` on a Windows App, only for Linux Profiler Preview. Does it still need to be done on Windows?

**Comment by xiaomi7732** [comment]
@johnrom I assume you are using the profiler described by this page: https://docs.microsoft.com/en-us/azure/azure-monitor/app/profiler-overview. Then, you don't need `services.AddServiceProfiler()`. 

What you need to do is:
At the beginning of the app, do this:

```csharp
    using System.Diagnostics;

    // Apply the workaround
    Activity.DefaultIdFormat = ActivityIdFormat.Hierarchical;
    Activity.ForceDefaultIdFormat = true;
```

Also, so that you know, there's a fix on the backen to address this. It will be roll out in couple of days given the testing goes well.

**Comment by xiaomi7732** [comment]
The issue has been fixed by 12/20/2019. Please remove the workaround.
