### ISSUE TITLE
Large TraceUpload20/30.zip files in project

### ISSUE THREAD

**Issue by SidShetye** [microsoft/ApplicationInsights-Profiler-AspNetCore#70]
After adding `Microsoft.ApplicationInsights.Profiler.AspNetCore` `2.0.0-beta4` we're seeing two large files that are added to our project 

`\ServiceProfiler\TraceUpload20.zip` 5MB and 
`\ServiceProfiler\TraceUpload30.zip` 4MB

Combined, they are about 1/5th of our docker image size so a couple of questions: 

1. Why are there *two* ? Both seem under the `netstandard2.0` build of `Microsoft.ApplicationInsights.Profiler.AspNetCore`, seems like only one should be distributed based on the requesting project's target, right?

2. Slightly tangential - if they're just uploaders, why are they so large?

**Comment by xiaomi7732** [comment]
@SidShetye Thanks for the feedback. This is the first time we got feedback about the uploader size. Give me some time to investigate this.

At the same time, we deliver both so that it will work for both .NET Core 2.x and .NET Core 3.x. If it would help, can you try deleting the other zip file after build the solution in the building environment?

**Comment by xiaomi7732** [comment]
Hey SidShetye, thanks again for your feedback. In [2.0.0-beta5](https://www.nuget.org/packages/Microsoft.ApplicationInsights.Profiler.AspNetCore/2.0.0-beta5), we reduced the uploader size to 5.7M for simsihp. We will keep looking for opportunists to reduce the size further.

**Comment by SidShetye** [comment]
Thanks, we haven't had a chance to audited our container size on beta5 yet. [This nuget document](https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks) about multi-targeting might also help.

**Comment by xiaomi7732** [comment]
@SidShetye Thanks again for the suggestion. The nuget packages has been updated to deliver different version of uploader for different target framework (actually, netstandard 2.0 vs netstandard 2.1).
The change will be in the next release unless we found block issues. I'll close this thread once the release is there.

**Comment by xiaomi7732** [comment]
Find the release in [v2.1.0-beta1](https://github.com/microsoft/ApplicationInsights-Profiler-AspNetCore/releases/tag/v2.1.0-beta1).
