### ISSUE TITLE
Add override to UseServiceProfiler for our own config

### ISSUE THREAD

**Issue by stweedie** [microsoft/ApplicationInsights-Profiler-AspNetCore#72]
Currently, there is no way to pass in a UserConfiguration instance. The only way to configure the profiler is by passing in my entire application's IConfiguration (which also assumes that the relevant config is stored on an arbitrary property in your appsettings.json ("ServiceProfiler"). or by passing an Action such that I set every property of the config manually.

Unless I have intimate knowledge of this library, I'm not able to easily discern how the profiler is being configured.

Consider:

```c#
services.AddServiceProfiler();
// how am I being configured? MAGIC
```

versus:
```c#
var serviceProfilerConfig = configuration.GetSection("WhateverIWantToCallThisSection")
  .Get<UserConfiguration>();
serviceProfilerConfig.IsEnabled = (environment != "Development");
services.AddServiceProfiler(serviceProfilerConfig);
```

The latter is much more explicit and easy to customize. It's also much clearer where / how the configuration is loaded.

**Comment by pharring** [comment]
I think you're supposed to do this:
```csharp
services.AddServiceProfiler(options => 
{
    // Configure options from the specified section
    configuration.Bind("WhateverIWantToCallThisSection", options);

    // Override the IsEnabled property
    options.IsEnabled = environment != "Development";
});
```
