### ISSUE TITLE
ANSI coloring of debug output

### ISSUE THREAD

**Issue by Eneuman** [microsoft/ApplicationInsights-Profiler-AspNetCore#76]
Reading the debug output of ServiceProfiler is hard because it's using ANSI coloring.
Visual Studio 2019 does not support ANSI coloring in debug window so the output looks like this:

[40m[37mdbug[39m[22m[49m: ServiceProfiler.EventPipe.Client.ServiceProfilerProvider[0]
      Entering StartServiceProfilerAsync.
[40m[37mdbug[39m[22m[49m: ServiceProfiler.EventPipe.Client.ServiceProfilerProvider[0]
      Trace: /tmp/4e918aef-39ec-472c-a237-18bb17b14df9.netperf

Since many packages are using ANSI coloring today, the best solution would be to make VS support it, but they for some reason does not see this as a issue.

Is there a way to enable/disable ANSI coloring from debug output?

**Comment by pharring** [comment]
The Console Logger has a ConsoleLoggerOptions.DisableColors property.
You should set it to 'true' in your configuration (appsettings.json)

**Comment by xiaomi7732** [comment]
@Eneuman I just want to follow up a bit since it has been days. Does the answer from @pharring solves your issue?

**Comment by Eneuman** [comment]
Yes it did!
Thanks @pharring

Really hope the VS team can fix colouring in the window. VS Code already got it.

________________________________
Från: Saar Shen <notifications@github.com>
Skickat: Tuesday, February 18, 2020 8:01:50 PM
Till: microsoft/ApplicationInsights-Profiler-AspNetCore <ApplicationInsights-Profiler-AspNetCore@noreply.github.com>
Kopia: Per Bornsjö <per.bornsjo@links.se>; Mention <mention@noreply.github.com>
Ämne: Re: [microsoft/ApplicationInsights-Profiler-AspNetCore] ANSI coloring of debug output (#76)


@Eneuman<https://github.com/Eneuman> I just want to follow up a bit since it has been days. Does the answer from @pharring<https://github.com/pharring> solves your issue?
