### ISSUE TITLE
AddServiceProfiler causes a crash if instrumentation key is not provided

### ISSUE THREAD

**Issue by skwasiborski** [microsoft/ApplicationInsights-Profiler-AspNetCore#79]
In case instrumentation key is not provided AddServiceProvider extension causes crash during asp.net core startup.

```
An unhandled exception of type 'System.ArgumentNullException' occurred in System.Private.CoreLib.dll: 'Value cannot be null.'
   at Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration..ctor(String instrumentationKey, ITelemetryChannel channel)
   at Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration..ctor(String instrumentationKey)
   at ServiceProfiler.EventPipe.Logging.EventPipeAppInsightsLogger..ctor(String instrumentationKey, ILoggerFactory loggerFactory, IHostingEnvironment hostingEnvironment)

```

**Comment by xiaomi7732** [comment]
@skwasiborski That behavior is expected because instrumentation key is an essential part of the system to work. What's your suggestion to form the behavior?

**Comment by skwasiborski** [comment]
Application Insights normally does not throw when the instrumentation key is not set. Arguably in server setup AI without instrumentation key is as useless as the profiler. 

Current behaviour means I cannot run my service locally without providing instrumentation key (which I do not want to do) or modifying my code which I also do not want to do. 

In my opinion it the profiler should not throw exceptions in any case, it may log a warning or something.

**Comment by xiaomi7732** [comment]
@skwasiborski, fair enough. I'll make a fix.

**Comment by xiaomi7732** [comment]
Fix available:
![image](https://user-images.githubusercontent.com/3674549/78056829-9860ce80-733a-11ea-9241-b8994a783ab6.png)
Will be rolled out within the next release.

**Comment by xiaomi7732** [comment]
Thanks again for the report. Fix released in:
* [Microsoft.ApplicationInsights.Profiler.AspNetCore/2.1.0-beta2](https://www.nuget.org/packages/Microsoft.ApplicationInsights.Profiler.AspNetCore/2.1.0-beta2)
