### ISSUE TITLE
AddServiceProfiler() overwrites ApplicationInsightsServiceOptions

### ISSUE THREAD

**Issue by uncleyo** [microsoft/ApplicationInsights-Profiler-AspNetCore#81]
I'm using the latest `2.1.0-beta1`.

The way `AddServiceProfiler()` is implemented internally (any of its overrides), it registers own `ApplicationInsightsServiceOptionsDefaultConfigurationMirror` as `IConfigureOptions<UserConfiguration>` in the service collection and eagerly uses that immediately.
Even if `AddApplicationInsightsTelemetry` has been called and is configured properly already at that point via configuration `Action<ApplicationInsightsServiceOptions>`.

This completely ignores the configuration layer hierarchy defined with custom `ConfigurationBuilder`, so it cannot pick configuration data from anywhere else outside "standard" configuration convention.

And unlike `UserConfiguration`, this eagerly internally obtained instance of `ApplicationInsightsServiceOptions` cannot be customized.

Ultimately, `AddApplicationInsightsTelemetry` shares the same flaw, but there it can at least be further customized via `Action<ApplicationInsightsServiceOptions>`, and in this case it cannot.

**Comment by xiaomi7732** [comment]
@uncleyo thanks for the report. I'll see what I can do.

**Comment by uncleyo** [comment]
To be honest, the whole assumption that `appsettings.json`/`appsettings.<env>.json`/`environment variables` is the only way you should configure an app is at odds with even some of MS products, like Azure App Configuration, not to mention User Secrets in Visual Studio and such.

And this should probably be addressed in `AddApplicationInsightsTelemetry` too.

**Comment by xiaomi7732** [comment]
Fix released in:
* [Microsoft.ApplicationInsights.Profiler.AspNetCore/2.1.0-beta2](https://www.nuget.org/packages/Microsoft.ApplicationInsights.Profiler.AspNetCore/2.1.0-beta2)
