### ISSUE TITLE
Matched sample count does not equal to gathered sample count

### ISSUE THREAD

**Issue by Eneuman** [microsoft/ApplicationInsights-Profiler-AspNetCore#90]
Hi,

There seem to be a problem with the validation of events in the ActivityListValidator
It only finds one event, no mather how many events that has been gathered.

I keep getting debug messages like this:
`Matched sample count does not equal to gathered sample count. Expected: 91, Actual: 1`

Otherwise, the Profiler seems to working fine:
`Debug: 1 events has been sent to AI as CustomEvents`

What does the ActivityListValidator actually do and why can it not match my gathered events?

My setup is this:
AKS + Application Insight Kubernetes enricher
Profiler version: 2.1.0-beta4
.Net Core 3.1
Using Azure Dev-Spaces

**Comment by xiaomi7732** [comment]
@Eneuman, what the validator do is to check if there's proper the start/stop events that could form up  the requests.
I'll see if I can repro the issue.

**Comment by xiaomi7732** [comment]
@Eneuman, could you please set the log level for Profiler to 'trace' and run it again? Then, paste the full logs here and I'll take a look.

```jsonc
{
  "Logging": {
    "LogLevel": {
...
      "Microsoft.ServiceProfiler": "Debug",
      "ServiceProfiler": "Trace" // trace logs
    }
  },
  "AllowedHosts": "*"
}
```

**Comment by Eneuman** [comment]
Hi and thanks for your quick reply

Here is the requested log.
[ServiceProfiler Log.txt](https://github.com/microsoft/ApplicationInsights-Profiler-AspNetCore/files/4769373/ServiceProfiler.Log.txt)

**Comment by xiaomi7732** [comment]
@Eneuman, thanks for providing the logs. I checked it, there are 2 interesting activities:
/#46/1/3/ & /#46/1/5/, however, the stop event were not found during the validation:
```
      [07:28:18] Hit on: /#46/1/3/. OpCode: Start, IsStartHit: True, IsStopHit: False
      [07:28:18] Hit on: /#46/1/5/. OpCode: Start, IsStartHit: True, IsStopHit: False
```
This is interesting. I need the trace to file to understand why the stop events were not there.

Can you set 'PreserveTraceFile' to true in the configuration and run it again? Toward the end of the logs, it will reveal where the trace file is saved to.

```jsonc
{
  "Logging": {
    "LogLevel": {
...
      "Microsoft.ServiceProfiler": "Debug",
      "ServiceProfiler": "Trace" // trace logs
    }
  },
  // Add the following section:
  "ServiceProfiler": {
    "PreserveTraceFile": true
  }
  "AllowedHosts": "*"
}
```
Then, could you please provide both the trace file and the logs?

**Comment by Eneuman** [comment]
Hi

Here are the logs as requested :)

[ServiceProfiler.zip](https://github.com/microsoft/ApplicationInsights-Profiler-AspNetCore/files/4772751/ServiceProfiler.zip)
[ServiceProfiler Log2.txt](https://github.com/microsoft/ApplicationInsights-Profiler-AspNetCore/files/4772753/ServiceProfiler.Log2.txt)

**Comment by xiaomi7732** [comment]
@Eneuman By the trace, I think I know what the issue is, the request you have finished `too fast`:

![image](https://user-images.githubusercontent.com/3674549/84539473-50e6af00-aca8-11ea-8b50-3a3f15e8c531.png)

My guess is either:
* The request does almost nothing, or
* There is an exception around the code trying to access service bus.

In any case, it leads to no valid request for performance analysis - thus the failure of the profiling session.

Does that make sense to you? Or am I missed anything?

**Comment by Eneuman** [comment]
I am using Azure Service Bus so I’m gonna see if I can trace any errors in there.

But it should be some other events in there as well since I made at least 20 calls to a api in that service. 

Any idea why these where not send?

**Comment by xiaomi7732** [comment]
Yes, you are right @Eneuman. Let me spend some time on why there's only 2 activities captured.

**Comment by xiaomi7732** [comment]
This is interesting. It looks like there's something going on on the .NET Core CLR that leads to the events being missed.
I am passing this on to @sywhang, whom works for .NET Core CLR team, to examine the code around EventPipe.

**Comment by xiaomi7732** [comment]
@Eneuman @sywhang is still helping reviewing the trace file. At the same time, any luck fixing the exceptions around the service bus?

**Comment by Eneuman** [comment]
@xiaomi7732 Yeah, it seems to be a internal thing in the Service Bus SDK. It throws a 409 when trying to access subscription rules.  There is a open thread about this. Any news about the trace file analysis ?

**Comment by xiaomi7732** [comment]
Hey @Eneuman It has been a while before any activity happened. I am sorry, I dropped the context on this already. **Feel free to reopen** or file a new issue if there's more discussion/troubleshooting needed.
